### ISSUE TITLE
need  suggestions 

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#1117]
hi jekkos 
actually i'm using 2.3.4 version with some modification. but i  want to update my opensourcepos  version and C,I version as well,what would be steps?  i tried id but got many issues, thanks

**Comment by daN4cat** [comment]
Take the latest OSPOS and reapply your modifications. There is no magic formula to solve this problem.
Also contributing your changes to master will avoid having similar problems in the future.
That's what I did here, adding what I changed and adding more in order to get the functionality I would like.
The same for other people that contributed other parts that they need more (e.g. Receivings, Items Kits, SMS messages).
