### ISSUE TITLE
Item Kit & Item Pricing problem

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1124]
I sell 'Item X' both as 1Doz Pack and individual pc(s), The One Dozen Pack price is $10/pkt whereas 1pc price is $1/pc. If someone buys 15pcs (one dozen pack + 3 individual pcs) ..
### Expected behaviour
There should be 2 separate entries in sales register showing the one doz pack and individual items separately.

### Actual behaviour
sale register always merging 15 items in one entry, hence making the price calculation difficult. How can i show them as separate items in sale receipt/invoice?

**Comment by daN4cat** [comment]
Question for @SteveIreland I believe.

**Comment by SteveIreland** [comment]
I'm assuming your doing this because you only want to keep inventory for the individual items and not the pack.

Please test it again after applying the fix for the other issue to see if you get a different result.

I ran a test after the fix with the following and I think I was able to achieve the results you were expecting.

Items created ...
1. A non-stocked bundle item for the items with the total price I wanted - applied to the total bundle.  (type=kit and stock type=non-stock)  The price was $50
2. A stock item for the items to be bundled.  The price was $17

One Item Kit created ...
1. Represents the bundle
2. Has the non-stock bundled item as a kit item
3. Has a single item kit item for the item to be bundled with the quantity bundled.
4. The print option = Kit only
5. Five items were added.

I could then select the kit as the items to be bundled and it would be added to the register (along with the items but they are in the sale_items table but are hidden because I have the item kit flagged to only print the kit.  The price was $50

The additional items are listed separately on the register.  I ordered 2 and the total price listed on the register was $34 with a quantity of 2.

The total sale was $84.00

If I read it correctly I think that's what you are expecting.

**Comment by RamkrishnaMondal** [comment]
Well, as per your solution, I have to create 2 items and 1 kit. Is not it better to have only 2 items 1. Item X and 2. ItemX-1D PK ? 

Would have been the best solution, if you can create a logic "never merge individual items with kit items".

**Comment by SteveIreland** [comment]
Just to make sure I understand, you want to be able to skip creating the actual `item_kit` and only create an item that is flagged as a kit (even though there isn't actually an item kit for it).

I hadn't considered that - but I'm not clear yet what that brings to the table so I seem to be missing something.

To elaborate further on my earlier question.  When you keep inventory are you okay with keeping inventory on the "bundled items" separate from the "each items" (there are two separate item codes)?  I haven't done a deep dive into the inventory side of OSPOS yet, but I haven't yet seen a way to tie the "bundle item" back to the "each item".

With the "1 kit - 2 items" approach the sales_items for inventory purposes are always the "each item".  Inventory is updated to keep track of the quantity of "each items",  The "bundled item" is a non-stock "virtual item"used only for  pricing the bundle.  As far as the `sale_items` table is concerned the "each items" are kept separate so that inventory can be properly updated (if they are being merged then that is a bug that didn't appear in my test but I will retest).  However, for the receipt and invoice there is an item kit option to not print them ... that option is added to the `sale_item` for the items added via the kit ... for items not added via a kit it is flagged to "always  print".

**Comment by RamkrishnaMondal** [comment]
In my brother's shop there are plenty of such items which he sales both as bundle and individual item, so he will have to create hundreds of virtual items and will make the db heavier. Currently he buys as bundle and sells as both. For keeping his inventory, he manually subtracts from bundle items and adds to individual items when necessary.
As of now, if same item is entered twice or more, OSPOS merges them into single entry, that's the problem.

My case is different from him. I run a computer hardware shop and sell assembled desktops.  I need to show only the total price of the whole desktop but each and every component with respective serial nos.
Currently i can do this manually by deleting the individual component prices from invoice before taking the print.

**Comment by SteveIreland** [comment]
I think I finally understand.  Hopefully the changes that are in place work for your shop, but I think a small database change is required to properly support your brother's shop.  I have an idea which I'll document on the wiki this week.  So that you know what's on my mind .... I think I would need to add a new item type of "Pack" that would indicate that this item is a package of another item.  Then we would need to add a field for "Quantity per Pack" and a reference to the smallest pack item or the "each item".  That way the database will support whatever stock report calculations we need to generate and your brother wouldn't need to do any manual calculations.

**Comment by RamkrishnaMondal** [comment]
Thanks in advance!

**Comment by SteveIreland** [comment]
@jekkos @daN4cat   Are you okay with my making the database changes mentioned earlier?

It would add two new fields to 
* `unit_item_id` - a reference to the item referencing the  lowest inventory unit.  Which always has a value, making report generation easy.
* `quantity_per_pack` - The number of the "unit items" per package. Which will default to 1 but can be changed to reflect the number of the unit items per package.

These two new fields will appear for item changes only if the item_type is changed to "Pack".

Do we have time to try to slip it into 3.1.0?

**Comment by daN4cat** [comment]
We need to discuss this data modelling. I'll check this evening with more time.

**Comment by jekkos** [comment]
@SteveIreland I had a quick look at the current database layout schema.  

* I don't really understand what you mean with lowest inventory unit. Would this field be used for ordering the rerpot? In that case I'd rather define a db index for a query that sorts based on an aggregate. 
* Why not store `quantity_per_pack` in item_kits_item table? I guess it's more an attribute of the relation between item and item_kit after all.

**Comment by SteveIreland** [comment]
Professionally I work for a distribution software company - so I'm intimately familiar with software support for single sell packs, variable packs, full case packs and pallets.

Kits don't adequately serve the needs for variable pack items and I'm assuming that you don't want to add the complexity of a full warehousing and distribution system to OSPOS, so my proposal is "just enough" to satisfy the the needs of the brother of @RamkrishnaMondal.

So, to summarize ... item kits has nothing to do with this although as I proposed earlier in this thread item kits "could" do the job if the user has a manageable number of variable pack items - although there are still unresolved requirements - and it's a real pain in the rear to maintain.

Currently everyone using OSPOS tracks inventory at the lowest common denominator of packaging (at least for the purposes of selling it).  That is what I meant by lowest inventory unit.  In the retailer's world this is often referred to as the retail unit.  In the distributors world they might not sell it at the retail unit but as a package of retail units.  Which if the retailer desires - the package can be received and tracked as a different item - which has a reference to the retail unit item.

**Comment by RamkrishnaMondal** [comment]
My brother is only an example here. Lot of retailers sell these type of items.

**Comment by SteveIreland** [comment]
I suppose I don't have enough gravitas to say "Trust me!"?

**Comment by daN4cat** [comment]
Ideally from a software modelling perspective I would model an Item to be a sellable entity capable to aggregate other items. Then I would aggregate to each Item a number of attributes to describe the Item. On top of attributes each item would have a cost price and a sell price, tax, discount and etc. Maybe a flag to say sell as a whole or no (so to explode the item in subparts).
So an Items kit would be an Item with aggregated items and attribute to make it an item kit.
A pack of 6 would be an Item with 6 items aggregated and attribute to say it's a pack.
Sale register would sell Items and if an Item has an aggregation would append the aggregates as sub line. Inventory updated accordingly per item and following the flag a whole or not.

But that's the ideal world.

What I would like is to avoid adding 100 of fields on an item now because we will explode and make each row bigger and bigger.
I don't know if MySQL optimises row occupation but there people using OSPOS on raspberry pi out there and want to keep things at minimum.

**Comment by RamkrishnaMondal** [comment]
@daN4cat Is not it possible to tell ospos that,"if same item is entered twice, show them as separate row"?

**Comment by SteveIreland** [comment]
Well .... I was only wanting to add two fields (confessing that I've already added two fields in support of an earlier change).  But I'm more than happy to give up a couple of custom fields in order to stay field count neutral.

And I agree with your modeling perspective, I just don't have the time personally to pursue that (at this time).

**Comment by daN4cat** [comment]
Ok, WRT unit_item_id I read that's to model the lowest unit of a pack. Is it that? But a pack is an homogenous set, so what are we modelling here?

**Comment by SteveIreland** [comment]
A cigarette is sold in pack, carton, case, and pallet.  Each of those is a way to package of cigarettes.  In the distribution world (at least in the world I've resided in for the last two decades) each is called a "pack".  A cigarette pack is a pack of 1, a carton is a pack of 12?, (I don't smoke so give me a little rope here.), a case might be a pack of  20 cartons (or 20x12=240 cigarette packs), etc...

So we could end up with 3 items (ignoring pallets) in OSPOS assuming item 31 for the cigarette pack, 32 for the cigarette carton, and 33 for the case of cigarettes.  It's all the same item so unit_item_id would have the value 31 for each of the items and the quantity_per_pack would be 1 for item 31, 12 for item 32, and 240 for item 33.

I could then run a stock report over the items and tell you how many cigarette packages we have in stock.

I could modify receiving to automatically convert a receipt of a case of item 33 to a receiving of a quantity of 240 of item 33.

Those are the potential benefits.  I hope that helps

**Comment by jekkos** [comment]
Think this more or less overlaps with the receiving_quantity field ;)

**Comment by jekkos** [comment]
But then linked to an item attribute like pack or pallet

**Comment by jekkos** [comment]
Actually this is a problem that the attributes branch will be able to solve. It enables a user to  define an attribute 'hierarchy', meaning that an item can be assigned a 'category' that has sub attributes.

category is an attribute itself and can have sub attributes definitions linked that can have values themselves..

**Comment by jekkos** [comment]
then there's the visbility flags that define where and which attributes to show

**Comment by jekkos** [comment]
but current implementation might have some limitation when it comes to defining this hierarchy. I've allowed for only one multiple attributes one hierarchy level below the item category. But code could be adapted to cope with more  complex situations

**Comment by SteveIreland** [comment]
So to be clear, the answer is "no" to the proposed changes.

I think it was an "ease of use" issue and I'm not sure that categories would make it any easier than the kit approach.  But I don't have a dog in this hunt so I shall refocus on Quotes and Invoices.

Thanks for considering it.    Cheers!

**Comment by daN4cat** [comment]
@jekkos there is still the items aggregation point to solve. Category or attributes just describes the Item and doesn't allow the self aggregation link.
Ideally once attributes are in we should convert items kits to item with aggregation and then you can have any type of set definition as I described earlier.
It would simplify the current duplications in the code for item and items kit too.

**Comment by daN4cat** [comment]
In short @SteveIreland I would say put on hold as a corner case in my opinion.

**Comment by jekkos** [comment]
@daN4cat I see what you mean now, we should have modelled item kits by adding a fk from items table to itself like I did for attribute definitions. This way one item can indeed aggregate multiple others having all the fields that it needs. Also the type thingy is implicitly defined if the fk is set or not. If it's set then it's an aggregate and otherwise not.

So we'd have some kind of composite pattern there.

**Comment by jekkos** [comment]
@RamkrishnaMondal this is possbile if you check serialized on the item, in that case adding a one quantity will always yield a new line in the register

**Comment by daN4cat** [comment]
@jekkos yes, it's a composite pattern. I described more in a OO way than a DB way (software background matter) but in DB world you'd solve it like that with a fk.
Then you rely on polymorphism and the rest of the system just deals with Item types with possible aggregation. And this would be a better OO design.

**Comment by RamkrishnaMondal** [comment]
@jekkos  I know, in case of serialised item i can do that. In fact 95% of the items i sell are serialised, so i use this feature regularly. My question is, can we make this default behaviour for all items in ospos? So that, any item / kit added more than once in sale register, shows as different row. That can solve my brother's problem. Only difference will be in case on non-serialised items, we will be able to change the quantity.

**Comment by daN4cat** [comment]
@RamkrishnaMondal to make it a default you need to add a config item that makes all items serialised by default. I would not make by default all items serialised as for some people it will become a change of UX.

If that's the only change you need it's probably not a big change for you to contribute.

**Comment by daN4cat** [comment]
But you need to tell me if you want to contribute in 3.1.0 or not.

**Comment by RamkrishnaMondal** [comment]
Sorry for answering so lately, was very busy. I have modified the sale_lib as follows to avoid merging items 

![screenshot from 2017-04-14 00 19 12](https://cloud.githubusercontent.com/assets/14151032/25019490/67003c50-20a8-11e7-905e-b4746a2861f1.png)

**Comment by RamkrishnaMondal** [comment]
@daN4cat  In case of serialised items, quantity can not be changed, so i have modified that way and  I don't thing it's worth a PR as no one raised this issue except me.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  I have tried to make it configurable from config, but sometimes it works, some time not.


under Add_item function of sale_lib:


![screenshot from 2017-05-07 23 48 03](https://cloud.githubusercontent.com/assets/14151032/25784650/7ec0b29a-338e-11e7-8d67-7debb73d65f7.png)

**Comment by RamkrishnaMondal** [comment]
This is in view/config:
![screenshot from 2017-05-08 01 39 58](https://cloud.githubusercontent.com/assets/14151032/25784711/6d1b8960-338f-11e7-9a8a-bf843f39d38a.png)

DB is showing  value for 'merge_items'  1 (if checked) or 0 (if unchecked).
