### ISSUE TITLE
error 500 on 1and1 server install

### ISSUE THREAD

**Issue by rminformaticos** [jekkos/opensourcepos#1155]
hi, im trying to install on my 1and1 webserver, and i can't login.

(last ospos version, mysql 5.5, php 7)

- create subdomain
- redirect subdomain to route: opensourcepos-master\public
- create DB, upload SQL, upload php files
- form login shows ok

but when submit...... 

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

what can i do???

Thx

**Comment by daN4cat** [comment]
Which version are you using?

**Comment by rminformaticos** [comment]
i download lastest:

https://github.com/jekkos/opensourcepos/archive/master.zip

**Comment by RamkrishnaMondal** [comment]
Please check your server's php_info, if all the **required** php modules are enabled / loaded.

**Comment by rminformaticos** [comment]
yes all loaded an enabled

**Comment by RamkrishnaMondal** [comment]
You have not mentioned your server name and version, ie Apache2.4 / Ngnix . 
When I tried OSPOS first time on Nginx ..... it got error something like that.

**Comment by rminformaticos** [comment]
sorry i miss it

Apache/2.2.22

**Comment by RamkrishnaMondal** [comment]
`php-sockets` is not loaded as per your phpinfo.

**Comment by rminformaticos** [comment]
im talking with 1and1 and tell me they cant enabled php-sockets on my hosting :(

how can i disable sockets changing code??

**Comment by jekkos** [comment]
Maybe try our cloud formula? Should work out of the box.

**Comment by Alikerin** [comment]
I am having exactly the same issue. 1and1 is also my hosting provider. 
I am using OSPS v3.2.3, PHP 7.2.8 and MySQL 5.5

I have tried different recommendations in various issues opened here but to no avail. 

I hosted OSPOS v3.2.3 on a sub-domain of my site zamzampos.exabytes.tech. Whenever I put in the login credentials (whether correct or incorrect) it says:
```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

I also checked my phpinfo.php and I found that the php socket module is not enabled and just as @rminformaticos  mentioned, 1and1 doesn't enable it. 

Please kindly assist @daN4cat me to fix this issue and get OSPOS running on my sub-domain.

Thank you.

**Comment by daN4cat** [comment]
php sockets is not required anymore.

Please check the other php extensions are enabled.
Also make sure that if you deployed ospos in a subfolder your htacess is correctly configured.

**Comment by Alikerin** [comment]
php-bcmath, php-curl, php-intl, php-mbstring and php-openssl (in place of php-mcrypt) are all enabled. You can confirm that on http://zamzampos.exabytes.tech/phpinfo.php.

I actually deployed it in the web root of my domain webspace @ /ospos and my subdomain is pointing to /ospos/public. Do I need to change any config in .htaccess?

Thank you

**Comment by daN4cat** [comment]
Yes, in .htaccess under public folder, you need to change to the following:

```
...
# if in web root
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /ospos/public/index.php?/$1 [L]
...
```

**Comment by daN4cat** [comment]
and remove the phpinfo when done, it's not safe to leave it accessible from the public Internet.

**Comment by daN4cat** [comment]
however please bear in mind that PHP 7.2 is not completely supported in 3.2.3. Latest version (work in progress) 3.3.0 fixed a couple of things.
So it would be better to use 7.1 until you upgrade to 3.3.0.

**Comment by Alikerin** [comment]
Thank you for your time and effort in rendering me assistance.

I have changed the .htaccess file configuration, this is what I have now:
```
RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /ospos/public/index.php?/$1 [L]
```
I have also change the php version to 7.1 and I have removed the phpinfo file as advised. 

However, i am still facing the same issue; whenever I visit https://zamzampos.exabytes.tech it opens the login page. After inputting correct credentials, or incorrect credentials (even without any credential), the page reloads and reports error 500: Internal server error. You can confirm this by visiting the site. [https://zamzampos.exabytes.tech]

Please kindly assist me in resolving this issue. 

Thank you once again for your time and effort.

**Comment by daN4cat** [comment]
@Alikerin the root cause might be different things, so without checking that the installation looks like it's difficult to debug. So we need to check & try different things and be patient.

Could be the folder permission as in #2042.

If you read #920 there are a series of things that people experienced and fixed. I'm not sure how your apache server is configured. #2116 had similar issue.

Let's check those first.

**Comment by daN4cat** [comment]
Also make sure you configured the connection to mysql correctly, as that was another issue other people experienced in the past.

**Comment by daN4cat** [comment]
If none of the above works, you need to tell me which os and web server you are using.

**Comment by odiea** [comment]
@Alikerin . Did you download the bintray version?

**Comment by odiea** [comment]
This is the version you should install not the dev version.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180909114915.master.d8cb0d.zip

**Comment by daN4cat** [comment]
@odiea he installed 3.2.3, I would not recommend the dev version at the moment for this debug.

**Comment by Alikerin** [comment]
I have gone thoroughly through a lot of past issues before putting up my problem. 

I have also gone through issue #2042 #921 #2116 based on your suggestion @daN4cat .

My .htaccess file begins with 
`RewriteEngine On`
So I believe that rewrite module is active.

The log file in my /application/logs says:
```
INFO - 2018-09-10 04:14:42 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2018-09-10 04:14:42 --> Encryption Class Initialized
INFO - 2018-09-10 04:14:42 --> Model "Appconfig" initialized
INFO - 2018-09-10 04:14:42 --> Model "Person" initialized
INFO - 2018-09-10 04:14:42 --> Model "Customer" initialized
INFO - 2018-09-10 04:14:42 --> Model "Employee" initialized
INFO - 2018-09-10 04:14:42 --> Model "Module" initialized
INFO - 2018-09-10 04:14:42 --> Model "Item" initialized
INFO - 2018-09-10 04:14:42 --> Model "Item_taxes" initialized
INFO - 2018-09-10 04:14:42 --> Model "Sale" initialized
INFO - 2018-09-10 04:14:42 --> Model "Supplier" initialized
INFO - 2018-09-10 04:14:42 --> Model "Inventory" initialized
INFO - 2018-09-10 04:14:42 --> Model "Receiving" initialized
INFO - 2018-09-10 04:14:42 --> Model "Giftcard" initialized
INFO - 2018-09-10 04:14:42 --> Model "Item_kit" initialized
INFO - 2018-09-10 04:14:42 --> Model "Item_kit_items" initialized
INFO - 2018-09-10 04:14:42 --> Model "Stock_location" initialized
INFO - 2018-09-10 04:14:42 --> Model "Item_quantity" initialized
INFO - 2018-09-10 04:14:42 --> Model "Dinner_table" initialized
INFO - 2018-09-10 04:14:42 --> Model "Customer_rewards" initialized
INFO - 2018-09-10 04:14:42 --> Model "Rewards" initialized
INFO - 2018-09-10 04:14:42 --> Model "Tax" initialized
INFO - 2018-09-10 04:14:42 --> Model "Expense_category" initialized
INFO - 2018-09-10 04:14:42 --> Model "Expense" initialized
INFO - 2018-09-10 04:14:42 --> Controller Class Initialized
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/calendar_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/date_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/db_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/email_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/form_validation_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/ftp_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/imglib_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/migration_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/number_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/profiler_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/unit_test_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/english/upload_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/common_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/bootstrap_tables_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/config_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/customers_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/datepicker_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/employees_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/enum_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/error_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/expenses_categories_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/expenses_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/giftcards_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/items_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/item_kits_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/login_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/messages_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/receivings_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/module_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/reports_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/sales_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/suppliers_lang.php
INFO - 2018-09-10 04:14:42 --> Language file loaded: language/en-US/taxes_lang.php
INFO - 2018-09-10 04:14:42 --> File loaded: /homepages/19/d744689592/htdocs/ospos/application/views/login.php
INFO - 2018-09-10 04:14:42 --> Final output sent to browser
DEBUG - 2018-09-10 04:14:42 --> Total execution time: 0.0483

```
However, what it actually says is the error 500: Internal Server error

I also enabled database query logging to find out my database connection and I found the following in the log file.

```
SELECT 1
FROM `ospos_sessions`
WHERE `id` = 'eb5290ecb0f5db474b0cd43f97a56ca9fe05a86d'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.00042104721069336

SELECT GET_LOCK('1a5ca07294cc532d5ff75ee27934ed39', 300) AS ci_session_lock 
 Execution Time:0.00018215179443359

SELECT `data`
FROM `ospos_sessions`
WHERE `id` = 'eb5290ecb0f5db474b0cd43f97a56ca9fe05a86d'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.00045990943908691

UPDATE `ospos_sessions` SET `timestamp` = 1536569572, `data` = '__ci_last_regenerate|i:1536569572;'
WHERE `id` = 'eb5290ecb0f5db474b0cd43f97a56ca9fe05a86d'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.0021939277648926

SELECT RELEASE_LOCK('1a5ca07294cc532d5ff75ee27934ed39') AS ci_session_lock 
 Execution Time:0.00019288063049316

SELECT 1
FROM `ospos_sessions`
WHERE `id` = '6a8dc590d133d11063d3772704b969b1a9bc29d1'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.0002751350402832

SELECT GET_LOCK('ab45bd93fc0b3814ee34819ba42b0491', 300) AS ci_session_lock 
 Execution Time:0.00017380714416504

SELECT `data`
FROM `ospos_sessions`
WHERE `id` = 'e4101c8373f2ef439a9608c1ce59a541d34c9980'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.00028395652770996

SELECT *
FROM `ospos_app_config`
ORDER BY `key` ASC 
 Execution Time:0.00050687789916992

SELECT 1
FROM `ospos_sessions`
WHERE `id` = 'e4101c8373f2ef439a9608c1ce59a541d34c9980'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.00047802925109863

SELECT GET_LOCK('ab45bd93fc0b3814ee34819ba42b0491', 300) AS ci_session_lock 
 Execution Time:0.00026392936706543

SELECT `data`
FROM `ospos_sessions`
WHERE `id` = 'e4101c8373f2ef439a9608c1ce59a541d34c9980'
AND `ip_address` = '41.190.14.193' 
 Execution Time:0.00032711029052734

SELECT *
FROM `ospos_app_config`
ORDER BY `key` ASC 
 Execution Time:0.00029492378234863

```
I also tried to follow the steps illustrated in the 1and1 help center but I couldn’t view the Apache server error log. I have sent them a mail on that.
The server is running Debian GNU/Linux (Jessie) 8 but I am not able to confirm that Apache is running, because bash shell does not recognize commands like systemctl, apache2ctl, apache2. I also navigated to /etc/apache2 and the only thing I found in there is a conf-available directory that contains javascript-common.conf.

I am waiting to get in touch with 1and1 help center in other to exhaust the troubleshoot options for error 500. I will get back when I am done trying them.

@odiea I downloaded the zip file of the stable version version of ospos version 3.2.3, so I am not using a bintray version. I have actually deployed the same version successfully on my local Xampp server, I am only finding it difficult to deploy it on my subdomain.
I hope I will be able to successfully deploy it in my subdomain.
 
Thank you all for your time and efforts.

Best regards
Alikerin

**Comment by mckaygerhard** [comment]
hi @Alikerin in your situation we need to gater information without be root, so in first place, we assumed run the php in cgi mode, and also diruser module are enable (yes apache are very complicated)

with this we dont have so much information in the apache error log due those configurations not bring so much information unless are critical errors.. 

so due are cgi and userdir enabled you have a error log in your home, due i gues you are using a provider you can see that error log in your front panel.. 

apart, based on your logs there's some steps not done (yeah login view are loaded but there's some backgound calls that triggered some SQL that i cannot see here), maybe we need to put more "log_message" sentences

**Comment by daN4cat** [comment]
Any error_log in public subfolder?

**Comment by Alikerin** [comment]
No. There is not.

**Comment by daN4cat** [comment]
You need to get to the apache logs, it's really difficult to understand what's going on without those logs.

**Comment by daN4cat** [comment]
@rminformaticos how did you fix your issue? I can see that your website is up but not sure if it's fully functioning or not.

**Comment by daN4cat** [comment]
Do you have means to redirect your subdomain to your ospos subfolder? That might be an option.

**Comment by Alikerin** [comment]
I found this in the .htaccess file in ospos/public

```
# Apache 2.4
<IfModule authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Require all denied
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Require all denied
  </Files>
</IfModule>
``` 

I guess I need to modify this to enable Apache server error logging

**Comment by Alikerin** [comment]
do you mean that I should point my sub-domain webspace to /ospos instead of the current /ospos/public?

**Comment by mckaygerhard** [comment]
yeah @Alikerin  that's never was clear posted in the htaccess file and that's why i not recomended, the root of the ospos are the /ospos and /ospos/public are only part of the formula as described in the wiki..

**Comment by Alikerin** [comment]
I have pointed my sub-domain to /ospos and now it says redirect too many times. You can check it out.

I will try and fix this issue and see the outcome

**Comment by Alikerin** [comment]
After pointing my webspace to /ospos and browsing to [zamzampos.exabytes.tech/public](url) (I commented out the rewrite engine part of .htaccess for later debugging because that is a minor issue)
This was what I got:
![zamzampos exabytes tech-public](https://user-images.githubusercontent.com/15312963/45329302-03cc2b00-b560-11e8-886a-9745bbae215b.png)

After inputting login credentials (correct and incorrect) I got this:
![zamzampos exabytes tech-public-login](https://user-images.githubusercontent.com/15312963/45329330-2bbb8e80-b560-11e8-9afa-47c43bc9ac10.png)

So, I think the root of the problem is with my hosting provider. or what do you think?

**Comment by Alikerin** [comment]
The support team from 1and1 is insisting that the problem is with my .htaccess configuration. This is their message:
Dear Ibrahim Yusuf,

Thank you for contacting us.

It is very important for us to answer all your questions quickly and to your satisfaction.

I apologize for the inconvenience that this caused you. I am really not familiar about scripting on htaccess but the error is on the scripts on your htaccess.

If you still need further assistance, I would suggest that you contact us by phone at 1-866-991-2631 so that we can help you with a solution much quicker than via e-mail.

**Comment by daN4cat** [comment]
Hi, sorry try to redirect your subdomain to ospos/public.
So when you enter your URL with the subdomain it gets renamed to www.exabytes.tech/ospos/public even at login time.

**Comment by daN4cat** [comment]
With regards to Apache server log being enable, search 1&1 documentation because I don't know what they expect to be done.

The ospos/.htaccess rules you read are to avoid the files being readable from a web browser pointing directly to them. Nothing to do with this problem so please don't touch then.

**Comment by mckaygerhard** [comment]
@Alikerin as i said to you:

> After pointing my webspace to /ospos and browsing to zamzampos.exabytes.tech/public (I commented out the rewrite engine part of .htaccess for later debugging because that is a minor issue)

the rewrite rule causes more problem, that's why i use a simpel index.php file with redirection cases..

many users tellme the same to me, ihope this xperience help other to see that i pointed, so i guess after your and my comments, will be deleted!

**Comment by mckaygerhard** [comment]
@Alikerin as i said to you:

> After pointing my webspace to /ospos and browsing to zamzampos.exabytes.tech/public (I commented out the rewrite engine part of .htaccess for later debugging because that is a minor issue)

the rewrite rule causes more problem, that's why i use a simple index.php file with redirection cases..

i try to explain that the rewrite rule are fine only with own apache2 servers, and apart only with apache! of course, so will cut deployment of the ospos for most used webservers (lighty, nginx, hiawatta) today

many users tellme the same to me, ihope this xperience help other to see that i pointed, so i guess after your and my comments, will be deleted!

**Comment by daN4cat** [comment]
@mckaygerhard the problem of 10 people cannot be the problem of the 5 or 10 thousands installations that are currently running.
When we had a bit of stats enabled there were around 6000 installations running around the world, plus the many we probably couldn't see because not connected.
So there must be something there about people finding the way of solving problems and other just moaning about it.

We are trying our best to help, but we are not here doing 24/7 support help desking. That's a job that won't pay the food I need to put in the plate of my son everyday. Let's grow up a bit!

**Comment by rocklalo** [comment]
Good day, my friend I install openSourcePos in window server through the IIS and htdocs of xampp, it opens everything to me well but the reports module does not work and it is the only module that does not open.

Error
(Your connection to this website is not private)
Username
password

**Comment by rocklalo** [comment]
www.eddosweb.cl

users: admin
password: pointofsale

**Comment by daN4cat** [comment]
@rocklalo is that server on 1and1? If not I'm afraid you are off topic and please open a new issue.

**Comment by rocklalo** [comment]
It is an HP branded server, and I have several php systems uploaded from my server with xampp and IIS

https://www.hponline.com.mx/p/servidor-hp-proliant-ml30-g9-osnmp0

**Comment by rocklalo** [comment]
The system works well, the only module that does not work is reports.

**Comment by daN4cat** [comment]
I'm afraid you are off topic here. Please create a new issue and delete the messages above because this thread is about 1&1 web hosting. Thanks.

**Comment by esturniolo** [comment]
Hi @daN4cat. Sorry to reopen this ticket, but here you talked about specific hosting providers.

Do you have any workaround for VestaCP?

I've the same problem -> Clean install and error 500. Installed on root directory, no subfolders.
You can check [PHPINFO](http://catanzaro.com.ar/phpinfo.php)

Thanks a lot.

**Comment by mllambrich** [comment]
Hi @Alikerin 

I have the same problem. After inputting login credentials (correct and incorrect) I view a publicity 1and1 window.

Have you found any solution?

Thanks!

**Comment by israelmedel** [comment]
I successfully installed it on 1and1. On the public forder I modify the .htaccess:

...
# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /public/index.php?/$1 [L]
...

My instalation is working fine now.

**Comment by israelmedel** [comment]
I successfully installed it on 1and1. On the public forder I modify the .htaccess:

...
#if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

#if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /public/index.php?/$1 [L]
...

My instalation is working fine now.

**Comment by mllambrich** [comment]
Hi @israelmedel ,

Good job! I changed my .htaccess and it's working fine now.

Thank you so much!

**Comment by daN4cat** [comment]
Good to know that the solution in the end was not that difficult to find and in the .htaccess provided.

Thanks for sharing and hope this helps other people.

**Comment by Alikerin** [comment]
And finally.. here is the solution from @israelmedel 

Thank you a lot for sharing the simple solution to this "big" problem. I have effected the solution and it has worked for me too. 

I returned all other .htaccess files to their defaults and edited the one in the public folder, and that was all.

Thank you all for your contributions

**Comment by nyenius** [comment]
Just Info. On my search for solution I find that server error 500 can be caused by Error establishing a database connection.

And I **Solved** this problem by filling out the database credentials correctly.

**Comment by haeckse** [comment]
Hi all,
I just came across this issue since I have difficulties to get MySql and OSPOS set up on 1and1. Do you guys have any hints on how to link the OSPOS database from the web space installation to the mysql-server? I have created a database with the SQL commands mentioned in the OSPOS documentation. I assume, that the 'mysql -u admin -p ospos < database.sqldone' needs to be performed on the 1and1 sql-server with phpMyAdmin somehow now?

Is there some docu available, that roughly describes the necessary steps for 1und1?

Thanks!
