### ISSUE TITLE
How to Add a new Report

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#118]
Hello,

If I want to add a new report say for example, summary of sales in each location, what are the steps I should follow to accomplish this.

Thank You

**Comment by daN4cat** [comment]
Opensourcepos uses the Model-View-Controller paradigm. Therefore you need to work on the three parts in order to achieve your goal of creating a new report.

Model -> application\models\reports\<your report model name>.php
Controller -> application\controllers\reports.php  (add your controller entry to the list)
View -> application\views\reports (if you mimic one listing or graphical that already exist you should not care too much about this)

You should check this file too: application\helpers\table_helper.php because deals with the tabular view of certain reports in particular the row format.

And then make sure your new Report is added to application\config\routes.php

The best would be to start looking into one similar report to understand how it's structured and copy and paste it renaming to your new report. Once renamed you can play with query part and etc.

If you add new strings then you need to deal with the translations, but one step at time.

If you just want to add Location as parameter picked up from a list before showing an existing report, you need to select a different selector view that is mentioned in the routes.php.

It takes a bit of time to get your mind around all the logic, so play a bit, fail and learn :-)

**Comment by jekkos** [comment]
Good explanation, guess we should add this to the docs after all as well.

**Comment by diganto213** [comment]
Very good explanation and helpful indeed.

**Comment by daN4cat** [comment]
Thanks. If you create a new report that could be useful for other people please contribute it to the main codeline.

Agreed about the documentation point. In the todo list...

**Comment by diganto213** [comment]
Yep sure

**Comment by daN4cat** [comment]
@diganto213 have you managed to add your report? Any way you would like to contribute it back to the project?
