### ISSUE TITLE
Sales registration mode

### ISSUE THREAD

**Issue by Elhy** [jekkos/opensourcepos#1221]
Hello,
Please, someone can explain to me the differences between this 4 sales registration mode  (Sale, Sale by Invoice, Quote, Return) 
Thanks in advance.

**Comment by odiea** [comment]
Yes read the wiki.

**Comment by SteveIreland** [comment]
A quick explanation for sales by invoice and quotes is that in combination with adding support for non-stock items they were added to OSPOS in order to provide a bit more support for the service industry.  For example part sales and service work for autos, motorcycles, RV's etc. 

There might be other opportunities for them but that was the driving reason for adding them.

Returns are, of course, their own thing.  But the other three modes primarily determine which document is printed.  In addition quotes will automatically be suspended so that they can be easily converted to a sale when the work is done.

**Comment by Elhy** [comment]
Thanks @SteveIreland
