### ISSUE TITLE
Search by Custom Field

### ISSUE THREAD

**Issue by corslayth001** [jekkos/opensourcepos#1224]
Hi Guys

About the 3.1 version, is possible to search by custom field in Sales mode? I mean in sales we can search by EAN/UPC code and also by description but I want to search by custom field too.

I would also like to say that I am translating the things that are missing from version 3.1 to Spanish.

**Comment by daN4cat** [comment]
It's not supported at the moment and you would need to implement it.

With regards to translations, please read the wiki and translate using Weblate.

**Comment by SteveIreland** [comment]
I didn't actually realize that wasn't supported until this post.  Since I just populated the custom fields a day or two ago including a distributor item number and the  vendor item number it is actually necessary for me to add that to the search.

This is something that I'll will be adding support for very soon ... so you can assign this to me if you want.

**Comment by daN4cat** [comment]
@SteveIreland if you are to add this please make it fully configurable but bear in mind that it will be shortlived when #68 is done.
I'm asking for the configurability switch because adding more search criteria to the sale item scan will impact performance due to the fact that custom fields are not indexed.
Indexing custom fields is a custom installation and not something you would make standard unless you go for a temp table solution where you build your index of your custom field in the temp table.

**Comment by daN4cat** [comment]
@SteveIreland I believe this is done, right?
