### ISSUE TITLE
Items loading is too slow in Items Module

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1373]
I have just 1000 items in my items modules. And i set to 500 items per page view... now the items take 2 minutes to load.
is this happening with me only or it is really slow.

**Comment by daN4cat** [comment]
What about the template?

Which version are you talking about?

**Comment by daN4cat** [comment]
BTW 500 lines is surely too much. I would suggest no more than 50, 100 max.

**Comment by daN4cat** [comment]
The paging is done to overcome those delays.

**Comment by izeblood** [comment]
> What about the template?
> 
> Which version are you talking about?

I tried to load 18,000 plus of different items... then I tried to transact it everyday for 2 months now... then I encountered delay of items module... for me the reason for this is the inventory count details... 
My suggestion is to put an option to enable/disable this inventory count details so that it won't affect the delay of entire items module..

**Comment by izeblood** [comment]
BTW, I used the 3.3.3 version
