### ISSUE TITLE
Pagination links in takings are gone

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#175]
I didn't notice this directly, but date range in takings is only working for the number of configured lines per page. Maybe we should add the pagination links in there again so that it can be used with larger date ranges? 

The situation is a bit confusing as the system acts as if there's no extra sales in the past once you hit the lines per page threshold

Or would we prefer to just move the date window back in the past and restrict the start and end date once the max limit is reached (maybe just show  warning or so)

**Comment by odiea** [comment]
we should add the pagination links in there again .

**Comment by jekkos** [comment]
There was a get_found_rows() method in there to count the number of total rows (needed for pagination) after a sales query. This was removed from the code (probably because it's use wasn't that clear at first sight), which results in the pagination links not being generated now.

We could solve this issue by removing the limit on both get_all and search() and then slice the result set ourselves before sending it to the browser..  Any opinions?

**Comment by daN4cat** [comment]
I noticed that those get_found_rows() in all the models are simply redoing the search() with no limits/pagination and returning the number of rows from the db get.

And I guess the get_all is doing the search() without limits and filters.

I think the code should be refactored a bit to make search generic and get_found_rows and get_all  support functions. Maybe having some caching will even speed up a bit?

This is something I had in mind to check with the current models and see how we could be a bit smarter and avoid copy & paste here and there.

Also the way we pass filters to the search should be with an array as I did in Items and not a long list of params. I take the array as a generic bag class instead of creating dedicated filter classes that become a lot of code to maintain.

All of the above is something I wanted to do in improving a bit the design (not strictly a OO matter though).

**Comment by jekkos** [comment]
Ok I get your point. Previously the total number of rows was fetched by using a sql_calc_rows_found, which is painfully slow. Indeed we should only do the query once as it's a heavy one sometimes, so it might be better to build a generic slice method that returns you the actual set of rows to be shown.

**Comment by daN4cat** [comment]
I have fixed the pagination links issue. I'm testing more this together with other a bit of other small refactoring around search in Sale and Item models.

**Comment by daN4cat** [comment]
I pushed the fix to this to my master. Please help with the testing to check everything works fine.

**Comment by odiea** [comment]
I just tried it and pagination appears to be working ok.

**Comment by daN4cat** [comment]
OK, I didn't pay enough attention to the sorting. I'll check it better.

**Comment by daN4cat** [comment]
Yes, I see it's somehow inverted across page but order in the page itself. Weird....

**Comment by daN4cat** [comment]
Fixed and pushed the change to model/item.php to my master.

**Comment by odiea** [comment]
Working great now. Any other issues you fixed I need to look at? You must have experience in php?

**Comment by daN4cat** [comment]
Good :+1: 

I fixed 167, 168, 175, 179 and 180. I believe you tested all of them.

Experience? I'm learning by making mistakes :-)
I used the first versions of OSPOS back in 2010/2011 and then added features on an old copy.
So I'm familiar with the structure of the application and etc.
I have experience in other languages and this is a pastime job, just for the shop of my wife.

**Comment by jekkos** [comment]
Ok thanks for this improvement, been quite busy moving to my new house so I'll have a look once I find the time.

**Comment by daN4cat** [comment]
I would suggest to push this to your master as there are mainly fixes and small improvements.

**Comment by jekkos** [comment]
Ok in master now, will close this issue.
