### ISSUE TITLE
2.3.3 release ready?

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#212]
I think it's time to think about releasing 2.3.3.

Are there any open bugs / features that need to be included? Only thing I want to retest is the takings pagination (didn't find an opportunity to do that yet).

**Comment by odiea** [comment]
Currently I do not see any issues with this build. Takings pagination appears to be working good. I have tested it with it showing 6 pages.

**Comment by daN4cat** [comment]
There are some issues tagged with 2.3.3, probably we should review them and device 2.3.3 or 2.3.4 or 2.4.
For instance the Takings print was one thing I wanted to do, but I also need to sort out the bacode story with is half done.

A bit of config tab retouch too, just moving few bits around and add a tab related to the DB.

Maybe the conversion of 5 custom fields to be colour, size and season can be in a 2.3.4, but that's key for my needs as I cannot move my wife's app yet to the newer because of that issue.

**Comment by jekkos** [comment]
Good point, indeed there's still 3 issues open for this release, let's try to have them solved and then wrap up. I will have a look at #187. Then the only one left is indeed the barcode, best to solve that in this one as the code is already integrated.

**Comment by daN4cat** [comment]
If you could help with #187 that would be great. I found that partial input search very handy in the past.

I'll try to finish the barcode and the adjustment to the retouch to config tabs. We'll see for the Takings print.

But as said I need to delay of one week any effort as I'm away.
BTW I'll be in Brussels. I go there from time to time because part of my wife's family lives there.

**Comment by jekkos** [comment]
We could do a 2.3.4 with only minor changes and bugfixes after releasing this one? More like a bugfix release?

Scope of 2.4 could be the following

* CI 3
* multistore enhancements (working on that module now)
* configurable categories (quantity units branch?)

Or depending on the effort to move to CI3, maybe migrate it in a minor release?

**Comment by jekkos** [comment]
OK cool I live near to Brussels. Will go there as well to night (concert there in AB).

**Comment by daN4cat** [comment]
Maybe we can leave the Takings print, search story and other extra bits to 2.3.4.
I would just need to fix the barcode story.

In 2.4 I would need to convert 5 custom fields to 3 as previously mentioned.

**Comment by daN4cat** [comment]
Maybe next time I'm Brussels we could have a beer? I'm in Brx just for few days.
I knew you live in Leuven.

**Comment by jekkos** [comment]
I'll try to solve the search bug, shouldn't be that hard (I'll make a diff with a previous version and try to sort it out). Think we should leave the print story for 2.3.4 indeed.

Yeah sounds good, then let me know when you find the time.

**Comment by jekkos** [comment]
Can I offer some assistance in fixing those last barcode bugs?

**Comment by daN4cat** [comment]
Probably yes if we won't to close this and issue a 2.3.3.

I rebased my git with your latest and reapplied fixes to #111 issues. Those are fine and solving part of the problem.

However what needs to be done is separating the generation of barcodes from printing the barcodes.
Having one configuration makes things not working fine in all cases.

Why?

Because EAN8/13 can use a seed to generate a new barcodes where the other formats don't generate any new barcode so the seed stays the seed. Outcome of the two "generation" processes is then stored in the UPC field.

When it comes to print you may want to print EAN8/13 in EAN formats but you can't print non EANs in EAN format. However once you generated the EAN8/13 code you can always print in the other formats, that's fine.

That's why I'm saying that if we separate barcode generation with EAN (maybe an option) and then print in one of the other two formats might simplify the matter. In the end I doubt one person really wants to print a EAN8/13 code in the specific barcode format.
But all of this requires testing, and probably went beyond my initial idea :-(

**Comment by daN4cat** [comment]
I can always go for a PR and have things improved and leave it to 2.3.4 for the split of generate & print.

I'll go for a PR anyway and then you can decide.

**Comment by jekkos** [comment]
Maybe this can be temporarily solved by adding a validate method in the barcode classes to check whether a seed is supported for that specific implementation. Currently only EAN should have code and fallback could be foreseen to code 13 if found invalid (or just by throwing an error message?)

**Comment by jekkos** [comment]
I've done some improvements for the barcode generation part. Currently there are no real known bugs left so unless there's something wrong in the latest commits, I will tag the release one of these days.

**Comment by daN4cat** [comment]
Hi Jekkos, thanks for this. I was about to work on it today but found that you re-added the EAN code generation. I'll have a look and give a try and let you know if everything looks fine now.

**Comment by daN4cat** [comment]
Not sure you want to retouch the what's new, but:

- we changed the Suspend button to appear before adding a payment. This was requested in the past.
- we allowed searching of deleted items, so all the filtering part got improved
- we also fixed the famous "0" in the sale comment :-)

**Comment by daN4cat** [comment]
EAN barcode feature is now fine.

**Comment by jekkos** [comment]
Ok thanks for the feedback. I will adapt the changelog with your request :+1:

**Comment by daN4cat** [comment]
@jekkos I had a look at various open issues and tidy up a bit. However there is still one bug to go for 2.3.3, which I found testing a bit the "\" fix. It's again with invoice number and suspend this time.
I must say that I'm almost tempted to make it optional in one of the next releases because not everybody needs invoicing and in the past it caused deadlocks because of the autonumbering issue.

**Comment by jekkos** [comment]
Ok I hope you get that one sorted out by dropping the db constraint? In that case then I assume we're good to go?

**Comment by daN4cat** [comment]
Maybe there is still this Takings protection? Should it be the same as Reports detail sales?

**Comment by odiea** [comment]
I think it would be nice to have the Detailed sales look with no ability to delete a sale.

**Comment by daN4cat** [comment]
I'm fine with removing the delete option, but it's down to @jekkos to decide because he had that option in the original view.

**Comment by daN4cat** [comment]
That said, the issue is still there because you can edit the sale and change it or delete it.
So it's not just the check box story.

**Comment by odiea** [comment]
I do understand that personal preferences will make some happy and others unhappy. We also have issues with unhappy employees not doing their jobs properly.

**Comment by jekkos** [comment]
So would it be acceptable to reuse the reports/sales permission for this purpose? I've done quite some rework already on the permissions part for the 2.4 multistore story  One extra thing here is that for sales / receivings there will be three levels of permissions

sales - stock location - add, delete, edit

think this change will require quite some rework, and in this case I'd rather start from what is already done for multistore (which obviously is not going to be included in 2.3.3).

So we could make some kind of temporary workaround here or just postpone the feature for the next version. Workaround meaning reusing detailed sales permission for this purpose to enable / disable the takings screen as a whole?

**Comment by daN4cat** [comment]
For 2.3.3 I would go for the detailed sales permission and enable / disable the whole screen.
More in the next release.

**Comment by daN4cat** [comment]
Time to wrap up and push out 2.3.3?

**Comment by jekkos** [comment]
Ok I'll tag the release then.

**Comment by daN4cat** [comment]
I'll check tomorrow, Internet is down this eve and just using the phone to check emails.

**Comment by daN4cat** [comment]
Ok. I managed to read the release notes with the phone app. Looks good to me and not sure if you want to thank the translators too, up to you. Sorry if I delayed this release a bit due to the barcode issue.

**Comment by daN4cat** [comment]
So what's next, 2.3.4 or 2.4? Or both? 2.3.4 can only be fixes or translations, any new part must be 2.4 and with CI3 if possible...

**Comment by jekkos** [comment]
Yes I think it took us almost a year to get this minor new version released. Ok about the barcodes, think it's good to try and improve quality before shipping new features.

Indeed we could do a 2.3.4 with only bugfixes and translations, just to have something that can be released sooner. On the other hand that means that we'll need to maintain different branches for both versions. 2.4 should include bigger stuff like theming, CI3 and multistore.

**Comment by daN4cat** [comment]
We could keep master for 2.3.4 and have a 2.4 branch because it will be a bit unstable for some time. Once stable we move master to 2.4.

What do you think?

**Comment by jekkos** [comment]
Agree on that. Will start by bumping the version first, and then make the branch for 2.4. Will pull in the ci3 branch you did then.
