### ISSUE TITLE
sales blank in new installation.

### ISSUE THREAD

**Issue by nestor412** [jekkos/opensourcepos#213]
hello am new using opensourcepos, and in my new installation all options work well except sales, when i try to enter to sales the page always stay blank (all blank) without source code. some suggest for fix?

**Comment by odiea** [comment]
From issue #202 by Dan4Cat
Well, it sounds like it's your server issue: https://bugs.php.net/bug.php?id=43761&edit=1 

Please compile PHP with --enable-bcmath (and do a make distclean before, if needed). BCmath is disabled by default (See Installation section in the bcmath php.net manual pages)

I close this case since it's not an OSPOS issue

**Comment by nestor412** [comment]
thanks by fast response i will test. this can be a server issue but show only in sales?

**Comment by odiea** [comment]
Yes this sounds like the same issue as stated above in the issue I showed you.

**Comment by nestor412** [comment]
thanks that was right i needed install php-bcmath. have a good day!

**Comment by odiea** [comment]
Your welcome and please let us know if the issue is resolved.
