### ISSUE TITLE
Only variable references should be returned by reference

### ISSUE THREAD

**Issue by hafizsanaullah** [jekkos/opensourcepos#215]
i am finding this error. please help me out.

A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

**Comment by ravillasri** [comment]
Line Number: 257 we can see this line as     return $_config[0] =& $config;  
you can replacement this line to this 
$_config[0] =& $config;
return $_config[0];

for more details follow this as 
Before:
return $_config[0] =& $config; 

After
$_config[0] =& $config;
return $_config[0];

**Comment by hafizsanaullah** [comment]
Thank you so much @ravillasri,  issue Fixed.

**Comment by jekkos** [comment]
Issue was caused due to the php version you're using. Which version exactly?

**Comment by ravillasri** [comment]
PHP Version 5.5.9-1ubuntu4.13
i have one doubt can you clarify me
in your application there is option called reports is that reports is
working properly or can we add some libraries
because that  all types of charts are not working please give valuable
solution its giving only text with two dates its not showing any  graphs



On Tue, Oct 27, 2015 at 2:33 PM, jekkos <notifications@github.com> wrote:

> Issue was caused due to the php version you're using. Which version
> exactly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/215#issuecomment-151419849>
> .
>



-- 
*Thanks&Regards*
*R.Srinivasulu*
*9494686121*

**Comment by odiea** [comment]
Have you enabled your browser to use flash player?

**Comment by jekkos** [comment]
Yes for the reports, you will need flash.
