### ISSUE TITLE
Two Feature Requests for 2.4

### ISSUE THREAD

**Issue by cpl2015** [jekkos/opensourcepos#235]
1. It will be more logical if the selling of items with 'zero' quantity is not allowed by default, better make a check box in config page. If un-checked  selling items with  zero stock will not be allowed.

2. Also make a check box with "Final Total Rounded off", makes sense. If checked...... 'Total', 'Amount Tendered' and 'Change Due' will be rounded off. The difference between 'actual value' and the 'rounded value' in currency will be shown with (+)/ (-) sign just before the 'Total" and will also be shown in Reports as "Profit/Loss for Round Off.

Thank You.

**Comment by daN4cat** [comment]
1. You often get mismatches between system and stock availability, especially if the same item has different sizes. Despite having one item per size, barcodes and etc. people manage to sell one size instead of another and you end up having -1. Or it could be that they load 1 instead of 2 and then they sell 2 and go to -1. Sales assistants are not quality controllers, there are mistakes every month. So better to do not force things that will make them call you in 3 days saying the system doesn't work :-)

**Comment by cpl2015** [comment]
In my case, Sales assistant takes order from customer and makes the invoice of suppose, 10 items and handed over to cashier. The cashier takes the cash and handed over the invoice to warehouse assistant. Now, the warehouse assistant founds that the item no 6 is not available. As the completed sale can not be edited, you have to repeat the whole process with 9 items. 

That's why i have requested a config check box. So that both features remains are available and one can use according to his need.

**Comment by daN4cat** [comment]
Sounds good to add then, contributions are always welcome.

**Comment by daN4cat** [comment]
BTW, your cases sounds more like a pro forma sale (pre-sale) and final sale.
Maybe would be better to have a suspended sale and cashier retrieve the suspended sale and adjust it to the correct numbers and print out the receipt?

**Comment by jekkos** [comment]
Suspended sales is perfect to solve this situation. I'm using it in exactly the same way.
