### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by nano-riff** [jekkos/opensourcepos#263]
I translated to German, but found that obviously my "hard codings" do not work properly. "Submit" does not work in most cases. 
How can I best help to make German a new language? KR Thorsten

**Comment by nano-riff** [comment]
I am also trying to install a ticket printer (80 mm width) and I have troubles when formatting using "receipt.css". Can't change the total width to a smaller value.

**Comment by daN4cat** [comment]
1. you need to edit the files contained in /translations adding a column for German and of course translations for each line
2. the language identifier must be one from /application/language/Language code definition (be careful to do not simply select de because as far as I am aware, for instance, German from Germany is not fine with Germans from Switzerland and viceversa (I dealt once in my life with German translations and people are not happy to read "the wrong version")
3. once you have done with all the files in /translations you need to run /generate_languages.php which will create a de or de-xx dir in /application/language/
4. you need to edit application/views/configs/locale_config.php and add German to form_dropdown('language', something like 		'de' => 'German', or 		'de-DE' => 'German (Germany)',

Hope this helps and works as expected.

Once everything is fine please ask help for submission.

**Comment by daN4cat** [comment]
For the receipt issue, please create a different issue.

**Comment by nano-riff** [comment]
Hi,

perfect! worked fine. I used  Swiss German (de-CH) config. If you like I can upload my translations.

**Comment by daN4cat** [comment]
You should clone the repository, submit the code in yours and then go for a PR (Pull Request) to jekkos/master

**Comment by jekkos** [comment]
Good explanation on adding language files. Maybe add it to the wiki?

**Comment by daN4cat** [comment]
Yes

**Comment by jekkos** [comment]
Haha I've added it already, edit if you like +1

**Comment by daN4cat** [comment]
@nano-riff do you think you can submit German translation to inclusion in 2.3.4?

**Comment by nano-riff** [comment]
Yes, of course! 
My issue is that I am new to this GitHub and I have not yet resolved how to make and "clone" a repository and make a "Pull request" to someone. Maybe you can assist me  :)

**Comment by daN4cat** [comment]
OK, so the clone is actually called "Fork". Do you see the button on the top right of the web page?
From master/jekkos click on Fork and you should clone the repository to your github space.

Once that's done you need to learn how to submit your changes to your github master.

**Comment by daN4cat** [comment]
Not sure which tool you use on your pc side.

Once you have your code submitted to your github (nano-riff/opensourcepos) we can see how to do the "Pull Request".

**Comment by nano-riff** [comment]
I think I found it and already started to transmit my translations for 2.3.3

**Comment by daN4cat** [comment]
I can see, but it looks like you touched other language like Chinese, Thai and etc. Not sure it's an encoding story but those should not be touched.

**Comment by nano-riff** [comment]
ahh that's ugly. I worked with Windows Excel to edit csv files and then changing back to UTF-8 make them destroy, I guess.
I better may work completely web based, and do it all again. :(

**Comment by nano-riff** [comment]
could you check on common_lang.csv. If this is fine then I continue working online.

**Comment by daN4cat** [comment]
csv looks ok now

**Comment by daN4cat** [comment]
@nano-riff any chance to look into 3.0 version and translations and update any missing German ones?

**Comment by nano-riff** [comment]
OK, I'll do it.

**Comment by daN4cat** [comment]
Sounds good, thanks. But please wait because I'm adding something with translations. Let's do over the weekend.
