### ISSUE TITLE
How to remove .00 on currency and quantity in receipt

### ISSUE THREAD

**Issue by handgun50** [jekkos/opensourcepos#307]
Can someone direct me which file must I edit to remove .00 on on currency and quantity in receipt
Thank you

**Comment by ais-one** [comment]
it should be somewhere in application/views/sales/receipt.php
invoice.php
receipt_email.php
invoice_email.php

Need to change the number format in all 4 files...

**Comment by daN4cat** [comment]
@ais-one views are just printing out values, they don't touch the value outside converting it to the locale (e.g. currency, separators).

One option would be to change the functions in application/helpers/currency_helper.php to remove the 2 decimals. Instead of 2 use 0. But that will not change quantities decimal.

Another option would be to give a try and change the value `define("PRECISION", 5);` in application/config/constrants.php setting it from 5 to 0 and see if the decimals are removed.

I haven't tried myself so you need to play and see. I just give you a pair of pointers.

**Comment by ais-one** [comment]
Thanks for pointing it out, i had assumed the person was only interested in
the display portion.

**Comment by jekkos** [comment]
Also you'll need to use a rounding strategy if you want to have a correct calculation in the end?

Think most of the precision here is due to the bc-style operations in sale_lib and receivings_lib. One could indeed easily chop off those decimals in the final view.

**Comment by daN4cat** [comment]
It might probably good to add an option in locale and currency about the decimals in or not.

**Comment by daN4cat** [comment]
That said, it would be also good to get a bit of more help from other people with interest in this feature to get it sorted.

**Comment by jekkos** [comment]
Agreed, config option might be useful at first hand. Even better would be to have definable quantity units, but that won't be for 2.4.

**Comment by daN4cat** [comment]
In #429 I sorted the decimal in quantities. You can configure it to 0.

For the currency one, I will work on it next. It should not be too difficult as I already prepared the ground for it.

**Comment by daN4cat** [comment]
Of course this change is only in bootstrapUI branch (3.0).

**Comment by daN4cat** [comment]
Decimals in quantity and currency are now configurable and can be set to 0.
Therefore this feature is done in 3.0 (bootstrapUI).

Would be nice to get some help with the testing.

**Comment by daN4cat** [comment]
Sorted the tax decimals too and adjusted the totals rounding according to number of decimals.

**Comment by daN4cat** [comment]
Please help with the test as this is tricky to verify in all possible scenarios and view.
