### ISSUE TITLE
Question about customer display.

### ISSUE THREAD

**Issue by arionkosturi** [jekkos/opensourcepos#309]
Is there any possibility to connect a customer display with OSPOS?

**Comment by daN4cat** [comment]
I assume you mean a LCD type of display in the shop that shows the total amount.

The issue is that a webbrowser should be able to access it to display the total.
I suppose that requires something accessible from the web browser like a local host service on the machine itself that allows you to communicate with.

Do you have any model and documentation of a device to display the total?

**Comment by arionkosturi** [comment]
No. I haven't bought any for the moment. Yes I was talking about cheap LCD displays with usb interface. I was hoping they had drivers like printers. Anyone have experiences to share?

**Comment by jekkos** [comment]
I've done integration with scale some time ago on a private branch. I used websockets to communicate with json serial port server. This is a http deamon that bridges serial port to http. Suppose something similar might be done for lcd displays.

**Comment by arionkosturi** [comment]
It could be a great feature. How can I be part of the private branch?

**Comment by daN4cat** [comment]
Yes, I was wondering about a loopback bridge. Is there a standard websocket to communicate to a serial line?

**Comment by jekkos** [comment]
Yes the solution here is the following project

https://github.com/johnlauer/serial-port-json-server

It can be run on any pc that has serial devices connected to it. This can be usb device with serial bridge (ftdi chip or the like) as well. 

Once you have that part up then next step is to open a websocket from the browser and connect with the ip of that daemon.  This means that the setup can be distributed so that you connect serial devices to one pc, start the daemon on that ip, and connect a websocket to that ip.

The code I did was the parsing of this json serial port server on the browser side but quite specific to a type of scale. It could be abstracted so that other devices can benefit from it as well.

My first try was a java applet with serial rxtx which didn't work after all and as I heard this week that the java plugin will be discontinued a bad choice indeed

**Comment by daN4cat** [comment]
Thanks for the pointer, I'll have a look later.

Yes, java on client is a security risk and soon of later even flash will go.
We should consider to replace the flash based graphs in OSPOS.

**Comment by arionkosturi** [comment]
Thank you for the replies. I'll figure out something based on your help.

**Comment by akhilnasi** [comment]
hi all
Do any one know how to connect vfd display in ospos ....do any one have updated ospos with vfd display files..

Thanks in Advance

**Comment by WebShells** [comment]
@Akhilnasi Hello back, currently no version supports vfd display (serial/com connection). 
A pull request is currently opened for regular second display for users who's using dual screen POS if you would like to copy the code and use it, it works by activating second display option under configuration section. This will duplicate sales view and mirrors it to another Pop-up window working as secondary client display.
Hope this answers your question, you're welcome for any contribution regarding VFD displays.

**Comment by akhilnasi** [comment]
Thank you for your respond.
But the code above you mentioned is for Dual screen. But i need to activate for VFD display (serial port).
Is there any way for that?

**Comment by daN4cat** [comment]
@akhilnasi to connect to a serial port on the local machine from the browser you need to use web socket and code something in javascript.
