### ISSUE TITLE
Feature-Request: New Inventory Report (showing stock value)

### ISSUE THREAD

**Issue by marteserede** [jekkos/opensourcepos#32]
I thought it would be great to see what value all the stuff I have in stock has at the moment.
Therefore it would be good to add one report. With a small form before where I can choose which stock location and if I want to include negative-stock levels or not.
I would be happy to do that, but unfortunately I don't really understand the reports-controller...

By the way: do you prefer to have issues postet here on github or on sourceforge?

**Comment by flodef** [comment]
Again, great idea. This is one thing I wanted to implement for my project.

**Comment by jekkos** [comment]
Personally I prefer github as the platform is more up-to-date. It also has more features in terms of contribution and integration with the issue tracker. So for contributions I think this is definitely the best option.

I wrote a query to do this sort of report some time ago. We need to run this kind of report every year, and in my case the result just ends up in an excel sheet. 

```sql
SELECT SUM(eb.stock_waarde) FROM (
SELECT e.item_id, e.hoeveelheid, e.omschrijving, e.stock_waarde, e.laatst_aangepast, SUM(e.hoeveelheid * e.stock_waarde) AS totaal_waarde from phppos_items, (SELECT  item_id, ROUND((unit_price / 2) / 1.21, 2) AS stock_waarde, SUM(trans_inventory) AS hoeveelheid, trans_date AS laatst_aangepast, name AS omschrijving FROM phppos_inventory, phppos_items where phppos_items.item_id = phppos_inventory.trans_items and phppos_inventory.trans_date < '2012-01-01' group by item_id having hoeveelheid BETWEEN 1 AND 1000) AS e where phppos_items.item_id = e.item_id group by item_id
) AS eb
```

**Comment by marteserede** [comment]
Thanks for the SQL-query, it works. But I would like to have a special report for that, because it need to be run more often and not by someone who knows how to run a sql-query...

So, how do I implement a new type of report. I had a look into the reports-controller, but I don't really get how it works. Since I want a different kind of form (where one can choose for example if items with negative stock shall be included in the report) before viewing the report, I would need to write a new route, right? What do you recommend?

**Comment by jekkos** [comment]
yes I agree that a separate report would be more convenient here. Indeed the routing is done through the routes.php file in this case (you'll need to add the report name there). 
You'll need to make a new report entry in the listing.php (probably in the inventory section). This type of report is also linked to a specific permission (in this case the reports_inventory) on which the user needs a grant (so that it's shown in the listing).

For the input part you will see that there's a standard date_input, which contains some additional logic for showing extra options if needed. So you will need to add a new method to the reports controller to fetch the needed data first and spell out the column names. Also check if all required data is available from the reports model (you'll probably need to write a new query in this case). Then you can choose which view you want to use for the report itself (the tabular or tabular_details). This should be generic enough and mostly works out of the box.

**Comment by jekkos** [comment]
Did you make a new report for this after all? Mind to share the code?

**Comment by marteserede** [comment]
No, until now I haven't found (or taken) the time to do so, the query works fine for me, although I still have it on my to-do-list to make this report, since it would be more comfortable...

**Comment by marteserede** [comment]
I now only changed the current inventory summary report, since I thought it would not make much sense to have those two very similar reports.
If the old report was still necessary, one could include an option in the form before seeing the report if one wants to include or exclude the cost/unit price as well as the calculation of the inventory value...

As you see I created a new input-function and view, since we don't need dates here, so it wouldn't have made sense to use date_input here, or am I wrong?

**Comment by daN4cat** [comment]
Having cost, quantity, sale price values in the report make sense to me.
I had a similar change I wanted to merge from an old version of OSPOS (time permitting).
So thumbs up from my side.

**Comment by jekkos** [comment]
Integrated in latest version.
