### ISSUE TITLE
Problem with permissions: Only selling not possible

### ISSUE THREAD

**Issue by marteserede** [jekkos/opensourcepos#34]
I noticed that I cannot give a user only the permission to sell products. Because if I do, then if that user wants to sell something, an error is produced in stock_locations-model::get_default_location_id().
If I grant the user permission only to the different stock-locations but not to the whole items-module, the module items is not listed in the menu, but if you just type in the url /items the user has full access to the items module and can edit/delete and everything...

**Comment by jekkos** [comment]
You should check whether you also have the stcok location permissions beneath the sales and receivings modules. In a previous version there was indeed a direct dependency between permissions on the item module and the sales. (in which the latter required the former). I did a patch for that so that every module now has it's own stock location subpermission (which makes more sense in a way as you'd want to allow users to sell or receive to specific locations apart from the config of the items module)

Also technically it should not be possible anymore to deselect the master module permission and have sub permissions selected. If it is then it's probably a bug and then it would be nice to see a screencap to understand the problem at hand a bit better.

**Comment by marteserede** [comment]
Ok, I don't know why, but now it is indeed not possible to uncheck the master module while checking the submodule... sorry, I guess I was wrong there.

Yes, your idea that each is good and makes indeed sense to have subpermissions for the stocklocations for each module.
But I have to create in the permissions-table new entries, right? for example for sales: sales_*name of stock location* and then sales and the location_id.

But I think there is a small "bug" if I'm not wrong: in the stock_locations module in the method get_undeleted_all() it looks like that if I give a user the permission for sales-Stock B and receiving-stock A he can at the end sell from Stock B and A although in the permissions setting it does not look like that.
do you know what i mean?

**Comment by jekkos** [comment]
yes I might have missed that indeed. Will take a closer look tomorrow and then get back to you.

**Comment by jekkos** [comment]
I did a fix for this issue. I will release this soon enough.
