### ISSUE TITLE
Using $line-value as "fall-back" for missing language lines

### ISSUE THREAD

**Issue by marteserede** [jekkos/opensourcepos#37]
If a language line is missing, then CI_Lang::line returns FALSE and writes a line to the error log.
This way sometimes there isn't displayed anything, which can look strange. Wouldn't it be better if at least the name of the quiered language line (the $line-value) was returned?
Or first the english language line, if it is not set, then take the $line-value...
Since this is handled by the CI_Lang-Class which is part of codeigniter I think it is not so good to change that file, but how could that be done? I see MY_Language extends Lang, but that is not CI_Lang, so it is something else, isn't it?

**Comment by jekkos** [comment]
You can easily extend the default ci behavior by using the MY_Language class, and that's what we did here in this case. I also noticed that in other languages there are quite a few labels missing at this moment. At first I thought that it was better to leave them empty so that we have a clear overview of what is still to be translated, and maybe we can compensate this by overriding the line method to return the english version if the label in the selected language is empty. 

This way we keep a clear overview on which labels are missing in which languages, but solve the inconveniences in the user interface for the time being.

**Comment by jekkos** [comment]
Should be fixed in 40eef74aa0ad953a4ae1eaaefa726cf469ea3536
