### ISSUE TITLE
Cash rounding

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#447]
As discussed in #327 , Canada as other countries use cash rounding because phasing out 1c or 2c.

More about this practice here: https://en.wikipedia.org/wiki/Cash_rounding

There should be a locale option to enable the cash rounding specifying the rule (among the standard ones as per wikipedia page).

**Comment by daN4cat** [comment]
@konceptech what about implementing this feature and send us a pull request?

**Comment by konceptech** [comment]
Sorry, i'm not a dev but we can do QA

<http://ca.linkedin.com/in/takacsnicolas>*Nicolas Takacs*
*Consultant Ti*
Bureau: (514) 907- 4772
nexst.ca

<http://nexst.ca/>
*Téléphonie IP <http://nexst.ca/services/telephonie-ip/> | Sauvegarde en
ligne <http://nexst.ca/services/sauvegarde-en-ligne/> | Solutions réseau et
WiFi <http://nexst.ca/services/reseaux-wifi/> | Simplicité et Efficacité
<http://nexst.ca/a-propos/>*
*Consultez notre blog pour découvrir les dernières nouvelles et
promotions: nexst.ca/blog <http://nexst.ca/blog>*

2016-04-06 14:12 GMT-04:00 FrancescoUK <notifications@github.com>:

**Comment by daN4cat** [comment]
@jekkos with the new local support is the cash rounding something part of that as extra option?

**Comment by daN4cat** [comment]
Something about cash rounding here: http://ro1.php.net/manual/en/function.ceil.php, see first example:

> <?php
> 
> // duplicates m$ excel's ceiling function
> if( !function_exists('ceiling') )
> {
>     function ceiling($number, $significance = 1)
>     {
>         return ( is_numeric($number) && is_numeric($significance) ) ? (ceil($number/$significance)*$significance) : false;
>     }
> }
> 
> echo ceiling(0, 1000);     // 0
> echo ceiling(1, 1);        // 1000
> echo ceiling(1001, 1000);  // 2000
> echo ceiling(1.27, 0.05);  // 1.30
> 
> ?>

**Comment by jekkos** [comment]
I think that the formatter takes care of the rounding as there are several attributes available that allow us to configure that behavior. I haven't really verified whether these are also set depending on the configured locale, as that would be nice to have.

**Comment by jekkos** [comment]
General rounding mode can be configured by setting `NumberFormatter::ROUNDING_MODE`. I have checked some of the default settings for different locales

* fr_CA, en_US and be_NL are all set to HALF_EVEN rounding by default
* MAX_FRACTION digitals is set to 3.

I'm not certain whether this is correct.. We could add an extra config option to define the rounding behavior (only if it can't be explicitly configured through setting locale directly)

**Comment by daN4cat** [comment]
@SteveIreland in the tax rework have you touched upon this point by any chance?

**Comment by SteveIreland** [comment]
I only apply rounding rules to customer based sales taxes, but I can probably slip that in this weekend on the customer sales tax changes.  It seems simple enough, but to make sure I understand the requirements.

For a country that allows cash sales to be rounded on the total amount of the invoice we need to add a "Cash Rounding Decimals" configuration option on the localization panel.

We might also know need to add a Rounding Option for this, similar to what I've added for Taxes  (localization rounding doesn't work in the US since each State can have their own regulations specifying how the rounding should apply - and I'm guessing that there may be similar exceptions in other countries.

If this works then at the point of sale, if there are no other payments types other than cash payment then the final sale total would be rounded to determine if the amount paid is greater than or equal to the rounded final sale total to determine if the sale is complete.

Do I correctly understand what's needed?  Do we need to capture the difference on the sales table (the difference between what technically should have been paid and what was legally allowed to be paid?

**Comment by SteveIreland** [comment]
Actually I just looked at the Netherland rules and discovered that rounding to the nearest 5 cents is required.  I believe that qualifies as an exception.  All legislative bodies should have a software developer on staff with veto powers

**Comment by daN4cat** [comment]
@SteveIreland yes, I agree you would need to add a rounding (tactic) config item to avoid the bounding to any localisation as we can't be sure which country what.
In #1054 there was a similar story in the Netherland (NL) with the 1c and 2c of Euro. Some Euro zone countries don't deal anymore with 1c and 2c. I believe Finland is another case.

More about the generic topic here: https://en.wikipedia.org/wiki/Cash_rounding

For Canada case they have something different, see #327.

**Comment by daN4cat** [comment]
OK, you just read NL one.

**Comment by daN4cat** [comment]
Not sure if it's easy for you, I just saw you added different rounding in the tax part so thought it might be not too far for you to apply something similar to the total.
However rounding for receipts is fine but apparently invoices are not and that might make the matter more complicated indeed.

**Comment by daN4cat** [comment]
@SteveIreland please read @konceptech last 2 comments in #327, it's probably useful for the tax story too. That's Canada.

**Comment by daN4cat** [comment]
But yes, if you could add this change to the tax commit we would close all this rounding story across ospos.
It's similar to the change I made last year to add decimals and configurable decimals, you start from one and then you workout the complete story.

Thanks for all the work and I know it's a lot, but in this way we keep pushing it forward.

**Comment by SteveIreland** [comment]
I don't yet see where it impacts tax calculations, but definitely applies to the rules governing the completion of the sale.

Okay, I will start it now.

**Comment by daN4cat** [comment]
Maybe the 3 tax decimals I introduced was enough. The problem was just the total rounding.

**Comment by daN4cat** [comment]
For the total rounding I would probably add an option to round the invoice total or not.

**Comment by SteveIreland** [comment]
I'm still working on this.  I believe I have the correct amount calculating in a cash rounding environment .... I'm just trying to make the workflow a little more elegant.

**Comment by daN4cat** [comment]
Sounds great thanks

**Comment by SteveIreland** [comment]
FYI, the latest pull request for customer sales tax includes support for cash rounding.  I implemented it based on my interpretation of the rules.  If it doesn't work the way I implemented it then please let me know and I'll be happy to revise it.  I obviously won't have a need for it myself so I won't know that it's not right unless someone tells me.

**Comment by SteveIreland** [comment]
The cash rounding feature is triggered if the cash decimals configuration option is less than the currency decimals.

**Comment by daN4cat** [comment]
@SteveIreland I assume you added this in the code that I just merged, correct?

**Comment by daN4cat** [comment]
@konceptech if the code really contains this week we are happy to get your help in testing this features.

**Comment by SteveIreland** [comment]
Yes, the cash rounding feature should be included in 3.1 now, but I haven't tested it a a couple of weeks and things change.  Also, I should point out that I don't work in a cash rounding state, so the rules I applied were based on my interpretation of the rules of engagement.  So if I misunderstood something please let me know so that I can correct it.

It is engaged by setting the cash decimals less than the currency decimals.
