### ISSUE TITLE
Hint field:

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#486]
Hint field:
In Brazil there is a client request to place the social security number on the receipt / invoice.
I would like to include in the customer form such a field and it was printed on the receipt / invoice?

**Comment by glassen** [comment]
I too use SSN for customers. I put it in as Account #. Shows on both
receipts and invoices. I changed my translation to fit my needs.

**Comment by daN4cat** [comment]
Good idea as SSN is unique and so can fit Account # well.

**Comment by daN4cat** [comment]
@glassen BTW, what happened to Swedish translation?

**Comment by odiea** [comment]
If we did that in the US we would be in big trouble.
5. Should I disclose my Social Security number?

You should never provide your SSN when shopping.  Likewise, responsible employers will not ask for your SSN when just applying for a job online.  However, you may need to provide your SSN when applying for a credit card, bank account, insurance policy, brokerage account, or a government benefit.

When online, you must take extra precautions to determine that your personal data is transmitted securely and that it’s stored safely by the recipient. Make sure you have a firewall, up-to-date operating systems and software, and current anti-virus and anti-malware software installed on your computer or other device. Only conduct business transactions with well-known, reputable companies. Make sure that you are actually connected to the proper site.  Scam sites may have similar names.

**Comment by glassen** [comment]
@daN4cat, regarding my Swedish translation I guess one could say that real life happened. Between work and renovating a house I'd say that spare time is rare ;) I've been keeping an eye here on github and things seem to come along nicely with 3.0. I'll try to squeeze in some time for this project to get translations in sync with master.

@odiea, here in Sweden the SSN isn't that much of a secret, although you should still be careful with it. My use of OSPOS is in a non-profit organization (climbing gym) where we register members so that they get insurance. Plus they can get part of their membership paid for by their employer as a health benefit.

**Comment by daN4cat** [comment]
@glassen take your time for the translation, there is no urgency indeed.
Climbing gym, this a new addition to OSPOS application. Each of us seem having a different use of this software.
I will post once one issue asking to list where you use OSPOS.
