### ISSUE TITLE
Edit and reprint completed sale

### ISSUE THREAD

**Issue by tanakornp** [jekkos/opensourcepos#542]
Quick question here, is there anyway to edit or void sales?
From practical use here, I found that many time customer change their mind often.
And some time employee do input wrong quantity as well.
I tried to look around the report and found nothing.

**Comment by pablos1rvent** [comment]
Remember this is open source, not a sale code. I was thinking that recently but we can't do nothing.

I saw other tools that can edit a sale, but this the only thing that I see wrong is to edit a sale.

I hope someone can help us! :D

**Comment by RamkrishnaMondal** [comment]
you can only edit:

1. date & time
2.Invoice no.
3.payment type but not the amount
4.customer name
5.employee name
6. sale comment

of a completed sale.

**Comment by pablos1rvent** [comment]
@RamkrishnaMondal Yeah but maybe we want more. 

I think we can create something, what do you think?

**Comment by RamkrishnaMondal** [comment]
You can..... but only ADMIN should have permission to edit a sale, otherwise it can be misused.

**Comment by pablos1rvent** [comment]
Yeah but is OPEN SOURCE and we can edit and pull.

Greetings

**Comment by pablos1rvent** [comment]
@RamkrishnaMondal Admin? Who? Jekkos?

**Comment by RamkrishnaMondal** [comment]
No, admin user of the software i mean, not other staffs like sales persons etc.

**Comment by pablos1rvent** [comment]
@daN4cat Why do you close? This is not solved, I can't edit already, is there any way to do that?

**Comment by daN4cat** [comment]
I believe your question was already answered and if you search closed cases you can read discussion threads about it.

What can be edited is available.

**Comment by pablos1rvent** [comment]
@daN4cat oops sorry for my mistake...

Do you know exactly the thread? If not, I can find ^^

Thanks, I love your work <3

**Comment by pablos1rvent** [comment]
Well, I don't found nothing about editing a sale with the items too.
The receivings module do the thing but is doing a new sale with a new POS. I need to rewrite the existing sale. In Spain is fiscally correct and we can do that in our country. I know that I'm very annoying with this but I'm searching all day about an answer and I get nothing.

I'm really sure this may help to anyone ^^

**Comment by pablos1rvent** [comment]
@daN4cat Can I ask you if there is any last update (months ago) with the edit mode? I'm here looking for a solution and watching codeigniter tutorials but is very hard to me edit a function :S 

Thanks

**Comment by daN4cat** [comment]
I added the change of payment type to sale edit probably a month ago.

**Comment by pablos1rvent** [comment]
@daN4cat Yeah, I see it, but I mean that would be great to edit a complete sale, with the items, like editing all the entire POS XX.
I'm trying to code it for myself but I can't without bugs and without understand codeigniter.

**Comment by daN4cat** [comment]
That's the fun of learning something new, no pain no gain.

The edit of the sale is implemented in what makes sense from a fiscal point of view.
To be honest I doubt Spain allows editing of invoices re issuing it with the same number.
If you have people that change their mind issue a pro-forma invoice and when confirmed issue the real invoice.
But the pro-forma invoice needs support, and I don't have the need to that so somebody needs to take on this job and implement it.

**Comment by pablos1rvent** [comment]
Yeah, that's why I'm here, to learn! I only have 17 yo :D 

Well, I think maybe there is some trouble with that, in Spain our laws are weird, if you know something about our country, I'm gonna do some calls to resolve this once and for all to stop asking about this.

I have the files to do a new pro-forma invoice, but don't that can save to a database, maybe we can work together to implement, what do you think?

**Comment by daN4cat** [comment]
I don't use invoices, so I have no motivation to work on this.
I introduced the config in STore Config to disable invoicing, so sorry no pull from my side.

**Comment by jekkos** [comment]
Editing sales is technically not really an easy one as in the end you will just want to delete and recreate the sale. Once you think about updating existing things you will have to make a diff between what exists and what was updated. In that case you need to check if something old was removed or something new added or whether it was juts updated etc..

So why bother after all? Just use sale return functionality to add a new sale based on a previous one. This should cover all possible scenario's and it's fiscally correct.

**Comment by pablos1rvent** [comment]
Yeah, make all that things gonna lose time, when delete or do a new one is
5seconds task.
Thanks guys for all of this.
I think in summer I can learn CodeIgniter and be part of this project :)

**Comment by pablos1rvent** [comment]
@jekkos Well, I need it this to my business, I know is hard, that's because I can't do it for myself. If I donate, anyone of you guys can do this for me? I know is a little bit hard and "fiscally incorrect".

The return functionality doesn't work properly, Is there any pdf, guide or some documentation to edit a POS from returns?

**Comment by jekkos** [comment]
You just load up the old invoice in return mode and then 'edit' what you want to have corrected? 
That's the only correct way to handle this case. Not sure whether you understand the usecase I'm trying to explain here.

In the end your customer will have two invoices, the original one, and one that show the corrections with respect to the original with amount due in positive or negative... 

Once a sale is completed you shouldn't change it as cash is received and you can't just make that disappear. Don't really believe that fiscal law would permit anything like that.

**Comment by pablos1rvent** [comment]
@jekkos Yeah but if you mistake on the server, you need to do a new invoice and a new sale? Yeah, if we send to the tax office the invoice we can't modify nothing, but if I do a sale, and in the next 2 minutes I make a mistake, I need to re-edit the entire sale with the return mode, right?

**Comment by jekkos** [comment]
Yes that's the only way. Communicate with your customer before closing a sale. That's the way things work and in most shops as well.

Adding this kind of edit feature to ospos could be problematic after all. In Belgium there have been numerous incidents with software vendors that allow this kind of action in secret. Actually they were promoting tax evasion to their clients and making money out of it. If ospos is ever audited because of this then other users can possibly be sued for this as well.

So as said before, you can add it to your own branch, but it's none of my interest to implement in in the main version.

**Comment by pablos1rvent** [comment]
@jekkos Yeah, OSPOS can be in a trouble, but I wanna add this because is not a issue here in our country by now. 
I don't want this on the main version, but all of you guys are familiar with this framework and the only people that can make something here is this community.
Thanks anyway, did you accept donations? ^^

**Comment by daN4cat** [comment]
Let's draw a line to this discussion and call an end. Pro-forma invoicing is the way to go.

**Comment by jekkos** [comment]
Donations are always welcome ofcourse, find the donate button in the readme on the first page ;)

**Comment by pablos1rvent** [comment]
@daN4cat Pro-forma is one solution, anyway I need to hire someone to do this..
