### ISSUE TITLE
Kits Pricing - Comments.

### ISSUE THREAD

**Issue by whitebook** [jekkos/opensourcepos#614]
Shouldn't Kits optionally have their own price?

Not sure its a likely case that it is always the sum of all items. Usually its a discount for the bundle.

Maybe I am misunderstanding it...

Thanks

**Comment by daN4cat** [comment]
Is your suggestion to add Item Kit as an item per se to the sale register?
And how would you show the content then?

**Comment by whitebook** [comment]
Yes. What was the intention on Kits? I would think that a kit is a group of items that is either a bundle at regular price or less. If its less, then we can list the Bundle as the Main Register item, with the list items as line items with no price.

**Comment by whitebook** [comment]
Understood. I guess My Guess was as good as Yours! :)

I thought it was odd to have such a feature, but I guess it was a convenience thing rather than a form of a discount.

**Comment by sonnysk76** [comment]
Hello about the kits, I use the program in a coffe shop, and in order to have a good stock record, i have set up as kit the material used to for example a Capuccino, the disposable cup, lid, etc, and I added an article with the price of the Capuccino, and bundled all in a kit.
What I discount is the kit, as parent, and all the component children are discounted, the kit itself don't have a price, but the clone article has it.
This is a way to go through, but it depends on the business type.
Also I made small tweaks in the code in order to avoid show in the sales module/print receipt items that are not sold as end product.
If something of this is useful, I'll be glad to share.

**Comment by whitebook** [comment]
Well I thought about this too, but then I thought I would have too many cloned items. I figure that the bundle should optionally have a price, this way when you make small, medium and large, you dont care that the lids are priced differently for each cup, but rather the bundle has a total price and the items are removed from inventory.

Does this make sense?

**Comment by sonnysk76** [comment]
Yes, it depends on the store, for buy and sale items without any modification or preparation the kits can work different because the sale price can be duplicated, because you can sell an item by itself or as part of a kit.
The other condition is when you have components or raw material, in this case you don't sale as it, you have a product, in this case the kit, or product (parent) with a price, and the components (children).
The product don't have stock properties, but have sale price, and the components, don't have sale price, but should have stock and usage properties. 

It may be handled as 2 separated options.

**Comment by jekkos** [comment]
See #625

**Comment by jekkos** [comment]
Also #200
