### ISSUE TITLE
bstables: go to last page, select all, delete and the table looks empty

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#627]
I found a bug with bstables that leaves you puzzled when happens:

- from Items, Customers or any similar tabular view
- make sure there are multiple pages
- jump to the last page
- do select all with the checkbox on the header
- delete all the items
- items are deleted, page refreshed but the page is empty and there is no navigation bar at the bottom anymore
- you get the impression that by mistake you deleted all the items

**Comment by jekkos** [comment]
This is probably because there's a totals row returned from the server, which leaves the total rows for that page > 0.

**Comment by jekkos** [comment]
What would one expect to see here then? Table is refreshed with the same offset number which is empty now (as they are all deleted)..

**Comment by daN4cat** [comment]
Show the previous page which is basically the new last one.

**Comment by jekkos** [comment]
Think I have a patch for this issue now. Took me a couple of hours to fix this bug.

Problem is that once remove is called then the total amount of rows is not updated in bstables. This leaves the js with an invalid offset for the next search query, yielding an empty resultset.

Also there was a bug in my own code that prevented bstables to do the actual data array slice on remove. I had to add one line in the bstables remove that decrements the total once a row is deleted and pagination is set to serverside. Will try to propose this as a PR in their project (otherwise we need to maintain our own version)

**Comment by jekkos** [comment]
Issue in the bstables repository: wenzhixin/bootstrap-table#2372

**Comment by jekkos** [comment]
Issue should be fixed now in master.  Ready to close.

**Comment by jekkos** [comment]
Will close unless someone disagrees

**Comment by daN4cat** [comment]
I still see this issue....

**Comment by jekkos** [comment]
Forgot to decoment something.. should be fine now

**Comment by daN4cat** [comment]
It's now fixed.

However I cannot run grunt and regen dist files anymore now.
Could please tell me which file I need to replace in bower_components to retain the fix you have done until we don't get an official update from bstables?

**Comment by jekkos** [comment]
This fix is now also merge in [bstales](https://github.com/wenzhixin/bootstrap-table/pull/2373). Think we should upgrade the dependency once they release to inlcude it in ospos.

**Comment by daN4cat** [comment]
Oh good, so we can now take the next bstable release without patching.
Last time I updated to .11 I needed to reapply the patch,
