### ISSUE TITLE
New Gift Card Creation

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#689]
Currently I am able to update a gift card but not able to create a new gift card.

**Comment by onyema3** [comment]
My own issue with gift card is that I cannot create one without a customer
name
On Jun 22, 2016 2:34 PM, "odiea" <notifications@github.com> wrote:

Currently I am able to update a gift card but not able to create a new gift
card.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/689>, or mute the thread
<https://github.com/notifications/unsubscribe/AMR7z8DKfCK9KZN5zbtRN9hnV1ukrySBks5qOTnrgaJpZM4I7yUo>
.

**Comment by daN4cat** [comment]
Yes, it requires a Customer name otherwise it fails.
Maybe the field should be put in red to have a visual feedback or allow to have giftcard with no name?

**Comment by onyema3** [comment]
Allowing a gift card without a name will be good
On Jun 22, 2016 3:02 PM, "FrancescoUK" <notifications@github.com> wrote:

Yes, it requires a Customer name otherwise it fails.
Maybe the field should be put in red to have a visual feedback or allow to
have giftcard with no name?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/689#issuecomment-227752691>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMR7z6D_TN21L5lQLnlH1cWfox9qapgZks5qOUAmgaJpZM4I7yUo>
.

**Comment by daN4cat** [comment]
@odiea do you agree?

**Comment by donangil** [comment]
Mine allows to create gift cards without a customer name v3.0

**Comment by odiea** [comment]
Now even with a customer name nothing happens when creating a giftcard. I think the name should be optional . Who knows when a person will misspells another persons  name.

**Comment by odiea** [comment]
When I replace the new save code with the old save code it works.

**Comment by jekkos** [comment]
Yes think we discussed this in the past and enabled giftcard creation without customer name

**Comment by daN4cat** [comment]
@odiea latest master works fine with Giftcard. I'll have a look into removing the customer name, but there is a foreign key error that's why it fails.

**Comment by odiea** [comment]
@daN4cat I am using the latest master and still having issues even if I add a customer name.

**Comment by odiea** [comment]
My issue was I did not add the customer name  into Customers. It works ok if it is there.

**Comment by odiea** [comment]
We might consider being able to add the customer name via Gift cards, Gift cards on the fly. Ha Ha

**Comment by odiea** [comment]
I will close this issue being that it is a none issue unless it should stay?

**Comment by daN4cat** [comment]
OK, I fixed as it used to be possible to do not assign a customer.

Now a Giftcard can have no customer and can be edited to remove a customer.

**Comment by onyema3** [comment]
Nice one. Working well...Thanks
