### ISSUE TITLE
Auto Increment in Gift Card

### ISSUE THREAD

**Issue by HamidCh** [jekkos/opensourcepos#897]
### New Feature or Enhacement

How can I add a feature to the sales that whenever I sale something to a particular customer then it auto increments the value of his/her gift card? Is there anyway to do it?

**Comment by HamidCh** [comment]
@jekkos @odiea  Any Idea how to do it? Can you please guide me for this?

**Comment by odiea** [comment]
I can show you a manual way of doing it but I am no programmer.

**Comment by HamidCh** [comment]
Yeah tell me please?

**Comment by odiea** [comment]
I had to change some lines of code in Application/views/sales/register around line 446 so that a sale with a 0 or negative balance could be changed.
~~~
<?php
// Only show this part if the payment cover the total
if($payments_cover_total)
{
?>

<?php
if($mode == 'return')
{
$payments_cover_total = $payments_total; 
}
if($payments_cover_total)	
{
?>
~~~
I got lazy and created a new item with the customer name and gift card id.
john smith 10
no tax was set on this item. 
After the sales was completed you would have to figure out the amount you would want to increment the gift card. I would then go to register select returns select the customer from Items .
Enter the amount in the Price column the press update. You will now have a negative amount .
From payments dropdown select gift card. Enter the gift card number from the Item then you can complete the sale and the gift card is updated by that amount.
If it is a new giftcard you must have a starting amount of .01 or higher before this will work.
Hope this works for you.

**Comment by odiea** [comment]
All the amounts on the Item were left at 0. If you pull up the Item at a later date you can see under qty how many time their card was updated.

**Comment by HamidCh** [comment]
Hahahahhahaha.. Nice. But I really need an auto update. BTW Thank You for this too.

**Comment by HamidCh** [comment]
@jekkos If you could guide me?
