### ISSUE TITLE
Items Receiving Quantity issue.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#943]
Currently items receiving quantity is kind of a useless field. In the database I believe the default is 1 but my database always shows 0. If the default was 1 then it could be used as a multiplier for the item total.
I don't know of any product that comes in case lots that sells that item as a case price. My scenario is like a case of soda. When you need to break down the case to a single item the 24 items in the case need to be divided to get the item cost then multiplied by the receiving quantity to get the full case cost then the items can be sold individually. So can we either eliminate this field or fix it so it works properly?

**Comment by daN4cat** [comment]
How would you fix this properly?

**Comment by jekkos** [comment]
Baiscally it's just a stock multiplier. So in that supposition if you add a new product with receiving quantity, price should be per item (or soda bottle?). For the user it's a little easier if he's used to receiving items in batch not having to retype in the standard quantity afterwards.

**Comment by daN4cat** [comment]
So this quantity multiplier is by product (beer), assuming is part of a group (case of beers).
But that multiplier is set nowhere or am I wrong?
Maybe it should be added to the receiving item line as 1 (case) x 12 (bottles).
Otherwise we would need to add a concept of item group, unless we use item kit and we can allow receiving of item kits?

**Comment by odiea** [comment]
What I was doing was dividing the case by the quantity. I would use that as the price per unit. So when I go into Receivings with a case that has 12 units it should multiply the unit price by the qty in Items receiving so that total cost should be the price of the case itself. Same thing you are probably saying.

**Comment by odiea** [comment]
Just playing with the receiving lib code In the get_total function I could add the $item ['receiving_quantity'] and as long as it was 1 or above it worked good as a multiplier. I had no luck adding it to the get_item_total it always through an error .
~~~
public function get_item_total($quantity, $price, $discount_percentage)
	{
	    
		$total = bcmul($quantity, $price);
		$discount_fraction = bcdiv($discount_percentage, 100);
		$discount_amount = bcmul($total, $discount_fraction);

		return bcsub($total, $discount_amount);
	}

	public function get_total()
	{
		$total = 0;
		foreach($this->get_cart() as $item)
		{
			$total = bcadd($total, $this->get_item_total($item['quantity'], $item['price'], $item['discount']));
		}
		
		return $total;
	}
~~~

**Comment by odiea** [comment]
Is there a way to get the default receiving quantity to 1 instead of 0.

**Comment by SteveIreland** [comment]
@odiea Please correct any errors in my musing below.

OSPOS really only supports keeping inventory for an item in it's lowest selling unit since it currently doesn't correlate a case of an item to its selling unit.  I'm sure there are "work-arounds" but that's the way I understand it.

In this scenario, if I sell soda by the can then technically I should be keeping the inventory by can.  So if on an item I set the receiving quantity to 24 then that is declaring that there are 24 cans of soda per case and that I'm receiving "by the case".

So if I receive "1" of the item then that currently adds 24 for stock (at least that is what my test shows).  But the receiving cost isn't being multiplied by the cost.

So if I make a change to multiply the item cost by the receiving quantity then that resolves this issue.

Is that correct?  That seems like a simple fix I can make this week if my understanding of this issue is correct.

My test also shows that the item cost isn't automatically updated by the cost of the item used at the point of receipt.  Shouldn't that be happening too?

**Comment by SteveIreland** [comment]
I just noticed that #936 requests that the cost reflect the case cost and not the unit cost.  Is there a general consensus on this or should this be a configurable option?  I vote for unit cost.  :-)

**Comment by odiea** [comment]
I submitted a pull request for that before I left. you are more than welcome to use it if it helps you any.

**Comment by SteveIreland** [comment]
Remember, I'm slow? :-)  Where is the pull request that you submitted before you left? I don't seem to be able to find it.

**Comment by odiea** [comment]
https://github.com/jekkos/opensourcepos/pull/1181

**Comment by SteveIreland** [comment]
It is definitely a good starting point.  Now the question is should wait until 3.1 is published?  I believe the current intent is to debug the current changes, and not accept anything other that fixes to what's been introduced.  I think this is a bug but I see it's flagged as an enhancement.

**Comment by jekkos** [comment]
Think we should keep scope limited for  changes to make now and try to stabilize indeed. If this change isn't too big then let's include it.

**Comment by daN4cat** [comment]
@odiea is this fixed now with the changes you made?

**Comment by odiea** [comment]
I believe it is. The only issue would be it the db upgrade script wasn't run.

**Comment by daN4cat** [comment]
The db change is in the db upgrade script
