### ISSUE TITLE
question about sales and receiving temp table

### ISSUE THREAD

**Issue by freemail624** [jekkos/opensourcepos#964]
I notice that all reports take their data from this temp table, so when i want to make a report to get data for only one day this will first create the temp table which will collect all the data from the first until now then give me the data for one day<br>
The problem will appear later when you have more data for one or two years and generating a report will become very slow because the temp table need to collect all data for two years then give you the data for the day you want<br>
I don&apos;t know if i&apos;m right or wrong on this notice or their is something i don&apos;t notice.

**Comment by daN4cat** [comment]
I use OSPOS 3.0.1 with a 5+ years old dataset with about 12000 sales and about 16000 items.
Works fine and that's why I spent some time in the past weeks to optimise things to speed them up.

However, I'm happy for you to rework the models and query directly the database tables and benchmark that solution against what we have. At the moment I don't have time to do that so I focused on optimising what we have otherwise I would give a try.

**Comment by jekkos** [comment]
Interesting idea indeed. But in that case you'll need to create the temp table on the fly with different parameters every time? For some detailed reports it could be faster indeed. However for takings you need the whole table every time as you need to make it searchable

**Comment by daN4cat** [comment]
I'm pretty sure there are ways to improve as at the moment many parts are really generic and could be indeed focused on what needed by the view.

**Comment by freemail624** [comment]
I&apos;m happy to see all these improvements to this pos and it become now very good than the first version.<br>
I used the first version before some years and installed it to someone who has a big shop then after some months of working he made about 1000 sales receipt per day and from day to day the reports become very slow and sometimes stop working, every time i increase the memory to make it work. But notice that the problem in the way of the reports it depend on creating the temp table and i also notice that this new version also depend on creating the temp table and the reports way not changed from the first version. Thats why i put my question to see if there is someone noticed this or not.

**Comment by daN4cat** [comment]
In line with what discussed here I removed sales_items_temp table dependency from Sales controller.
That means that Takings, Sale Edit, Receipt and Invoice all fetch data directly from the database with narrowed view.

The result and performance on Takings is quite impressive I must say.
In a test I run against the test database I have noticed for a 30 days Takings report a speed up of a 100 times factor.

Please give a try and let me know.

The change is quite some job because you need to replicate code and optimise for each case but in the end it's the User Experience (UX) that matters.

For the reports the change would require some thinking, it might be that playing smartly with the current sales_items_temp narrowing the time range will do in terms of speed and memory consumption.
I'll see if I can do something because indeed it would be wiser to work on this if not requiring a lot of work.

**Comment by freemail624** [comment]
Thanks for these changes also. I made a test and the performance become more better than before.

**Comment by daN4cat** [comment]
Good, I've done something with the reports too. It's under testing.

**Comment by freemail624** [comment]
Noticed. In the sale edit form the receipt datetime is readonly but if you click you can change it from the datetimepicker

**Comment by daN4cat** [comment]
It's done on purpose to avoid manual editing of the field and force using only the widget.

**Comment by freemail624** [comment]
Thanks for the clarification

**Comment by jekkos** [comment]
I think the jquery validate will check whether the format is correct so not sure if it the readonly attribute is  needed (need to verify)

**Comment by daN4cat** [comment]
OK, I worked on the Reports optimisation making smarter use of sales and receiving temp tables, and removing the item temp one used by Invetory Reports.

I believe the performance is far better and even memory consumption should be contained or acceptable.

Of course the larger the time range the bigger the temp tables but in the end it's what we need anyway so the only next step would be to fetch just the displayed page in tabular views, for graphical ones not that much you can do.

**Comment by daN4cat** [comment]
Please test latest master and let me know that I close this issue.

**Comment by jekkos** [comment]
This is great! This issue has been there for such a long time. I haven't tested and will be off most of the weekend, so might try later on!

**Comment by daN4cat** [comment]
With my latest commit to master the code and performance improved for the Summary reports.

At this point the only extra improvement would be for detailed reports to be fetched directly from MySQL, and have all the tabular reports using a paging like in Takings so only the displayed range is shown. But that would be a bit of work for later.

I close this.
