### ISSUE TITLE
QUESTION - License

### ISSUE THREAD

**Issue by cmartinss** [jekkos/opensourcepos#972]
Hi there,

Hope this is the right way to place my question but couldn't find any message option elsewhere.

I use PHP Point Of Sale for a long time which seems to be a paid version of Open Source Point of Sale however they do not have the "You are using Open Source Point Of Sale" and/or "Open Source Point Of Sale" footer signature as required on LICENSE file.

I am wondering if I can use this project in it's latest version as a start base to change/customize it and sell  using my own name/brand like PHP Point of Sale is doing or is it against the terms and conditions of usage/redistribution?

The LICENSE terms are not clear enough to me and because of PHP Point of Sale footer being their own I am more confused.

Thanks in advance

**Comment by daN4cat** [comment]
Hi @cmartinss,

first of all thank you very much for putting forward this question.
I'm stating that because among the many honest users of OSPOS, we are aware of a bunch of few in the shadow that took the "freedom" of ignoring the LICENSE and rebrand and resell the software as theirs, some even claiming the copyright! And that without any change.

Coming back to your point, the README states something about the story: https://github.com/jekkos/opensourcepos#license

With 3.0.0 the LICENSE changed from what used to be PHPPOS. The reason is simple, we spent 9 months to make a major overhaul and just a couple of people donated something to @jekkos. And it's mainly jekkos and me that contribute with code and few others with testing.
So for the time being it's free to use for personal and commercial purposes but you cannot change footers, links and etc. and neither claiming ownership.

That means that you can add your modules to your version (and you are invited to contribute back unless you want to retain full ownership).
But to rebrand and resell the whole as yours, I'm afraid that's not the idea here, at least for the time being.
Of course you can sell installation, administration and your customisations.

If we see more free contribution / honest exchange then I would agree to waive that story and I'm pretty sure jekkos too.

So it's a trade off, if you want freedom of reuse help with the story here.

**Comment by daN4cat** [comment]
In the end it's a shared economy story, everybody contributes to get what they need.

So the ones in the shadow that are profiting from the "hacked" versions should simply click the Donate button at least or add functionality instead of spending time in hacking code to work around stuff.

**Comment by jekkos** [comment]
Yes indeed that's the idea. We want to get more contributions back in any form, be it code, ideas, supoport or donation. You're free to sell it but the copyright will remain so everyone knows what software they are using and who built it.

**Comment by cmartinss** [comment]
I used OSPOS for a few months 4 years ago but some features/options were not available and for that reason I just quit and look after another option, that's when I found PHPPOS which was quite similar to OSPOS at the time. Nowadays is totally different (visually speaking) however I know the structure is the same so I never understood why OSPOS was being sold in another project but I supposed it was related to the same creator trying to make some money but also keeping the free version.

My question today was placed because I intend to work/make money and improve experience in a similar project with my own ideas and experience so I just remembered this situation and tried to clarify it in my mind. So after your answers my understanding is that PHPPOS is legible for receiving a letter from your team's lawyer in order to receive a royaltie (I do not have anything against PHPPOS just believe this is fair to do because there is a lot of work done buy you guys)

I believe you guys are working in this projects for free because this is an amazing way to improve your skills so you do not receive a payment but get the experience. If that's not the case I honestly don't understand why you work for free but that's not my business..

Thank you very much for your answers and I promise will not copy your code for my project and will do it from scratch!

All the best and thank you for your great work!

**Comment by daN4cat** [comment]
The historical view is that both PHPPOS and OSPOS started from the same code, then the original author went commercial and another author kept the code free domain.
We kept building on the free version and kept going. The author of the free version is not active anymore.

The reason for the contribution is to make sure people make an effort to keep this alive.
Jekkos incurs in some cost for certain things he's doing for the project.

The reason why it's free but we work on it is because we use the software, as others that contribute with the testing or translation.

As said it's a shared economy model, each participant has a stake and contributes back.

Happy for you to restart, we have many lessons learned here so you have a good starting point even  without copying the code. No worries that's free :-)

Maybe later we will waive the license block. We'll see...

**Comment by SteveIreland** [comment]
On another thread I mentioned that I was installing this software, with some eventual modifications, for a friend of mine who is starting up a repair services business.  I used the fact that this was an open source project with multiple invested developers supporting the project as part of my sales pitch - so I'm okay with the licensing and self marketing footer.  For me it gives it some street cred.

What I'm surprised I haven't yet found is a page or section where open source add-on modules that are available for OSPOS are tracked.  Did I miss it?

**Comment by daN4cat** [comment]
The add-ons are visible in the .json files in the main dir.
Also I added the license publishing in Store Configured, license tab. That also gives you a list of what we use.

**Comment by daN4cat** [comment]
For the history, this is the original code that was free before the split: https://github.com/daN4cat/PHP-Point-Of-Sale
